<?php

if (!function_exists('applyTheme')) {
    function applyTheme($theme)
    {
        $themes = [
        'pourple' => [            
            'Border_bottons_and_selected' => '#291F40',
            'bonus_color_dep' => '#291F40',
            'color_players' => '#291F40',
            'back_sub_color' => '#291F40',
            'botao_deposito_background_nav' => '#291F40',
            'botao_login_background_nav' => '#291F40',
            'botao_login_background_modal' => '#291F40',
            'botao_registro_background_modal' => '#291F40',
            'botao_registro_border_nav' => '#291F40',
            'botao_deposito_border_saq' => '#291F40',
            'botao_deposito_background_dep' => '#291F40',
            'botao_deposito_border_dep' => '#291F40',
            'botao_deposito_background_saq' => '#291F40',

            'search_back' => '#58418C',
            'placeholder_background' => '#58418C',
            'card_transaction' => '#58418C',
            'background_color_category' => '#58418C',
            'background_bottom_navigation' => '#58418C',
            'background_bottom_navigation_dark' => '#58418C',
            'footer_color' => '#58418C',
            'footer_color_dark' => '#58418C',
            'side_menu' => '#58418C',
            'side_menu_dark' => '#58418C',
            'navtop_color' => '#58418C',
            'navtop_color_dark' => '#58418C',

            'item_sub_color' => '#6B53A2',
            'background_color_jackpot' => '#6B53A2',
            'value_color_jackpot' => '#6B53A2',
            'sidebar_color' => '#6B53A2',
            'sidebar_color_dark' => '#6B53A2',
            'background_base' => '#6B53A2',
            'background_base_dark' => '#6B53A2',
            'background_color_cassino' => '#6B53A2',

            'search_border_color' => '#8870B8',
            'borders_and_dividers_colors' => '#8870B8'                       
        ],

        'black' => [

            'Border_bottons_and_selected' => '#2FA33F',
            'bonus_color_dep' => '#2FA33F',
            'color_players' => '#2FA33F',
            'back_sub_color' => '#2FA33F',
            'botao_deposito_background_nav' => '#2FA33F',
            'botao_login_background_nav' => '#2FA33F',
            'botao_login_background_modal' => '#2FA33F',
            'botao_registro_background_modal' => '#2FA33F',
            'botao_registro_border_nav' => '#2FA33F',
            'botao_deposito_border_saq' => '#2FA33F',
            'botao_deposito_background_dep' => '#2FA33F',
            'botao_deposito_border_dep' => '#2FA33F',
            'botao_deposito_background_saq' => '#2FA33F',

            'search_back' => '#161D29',
            'placeholder_background' => '#161D29',
            'card_transaction' => '#161D29',
            'background_color_category' => '#161D29',
            'background_bottom_navigation' => '#161D29',
            'background_bottom_navigation_dark' => '#161D29',
            'footer_color' => '#161D29',
            'footer_color_dark' => '#161D29',
            'side_menu' => '#161D29',
            'side_menu_dark' => '#161D29',
            'navtop_color' => '#161D29',
            'navtop_color_dark' => '#161D29',

            'item_sub_color' => '#0D131C',
            'background_color_jackpot' => '#0D131C',
            'value_color_jackpot' => '#0D131C',
            'sidebar_color' => '#0D131C',
            'sidebar_color_dark' => '#0D131C',
            'background_base' => '#0D131C',
            'background_base_dark' => '#0D131C',
            'background_color_cassino' => '#0D131C',

            'search_border_color' => '#6D7A91',
            'borders_and_dividers_colors' => '#6D7A91'  

        ],
        'blue' => [

            'Border_bottons_and_selected' => '#2FA33F',
            'bonus_color_dep' => '#2FA33F',
            'color_players' => '#2FA33F',
            'back_sub_color' => '#2FA33F',
            'botao_deposito_background_nav' => '#2FA33F',
            'botao_login_background_nav' => '#2FA33F',
            'botao_login_background_modal' => '#2FA33F',
            'botao_registro_background_modal' => '#2FA33F',
            'botao_registro_border_nav' => '#2FA33F',
            'botao_deposito_border_saq' => '#2FA33F',
            'botao_deposito_background_dep' => '#2FA33F',
            'botao_deposito_border_dep' => '#2FA33F',
            'botao_deposito_background_saq' => '#2FA33F',

            'search_back' => '#092C71',
            'placeholder_background' => '#092C71',
            'card_transaction' => '#092C71',
            'background_color_category' => '#092C71',
            'background_bottom_navigation' => '#092C71',
            'background_bottom_navigation_dark' => '#092C71',
            'footer_color' => '#092C71',
            'footer_color_dark' => '#092C71',
            'side_menu' => '#092C71',
            'side_menu_dark' => '#092C71',
            'navtop_color' => '#092C71',
            'navtop_color_dark' => '#092C71',

            'item_sub_color' => '#0C3588',
            'background_color_jackpot' => '#0C3588',
            'value_color_jackpot' => '#0C3588',
            'sidebar_color' => '#0C3588',
            'sidebar_color_dark' => '#0C3588',
            'background_base' => '#0C3588',
            'background_base_dark' => '#0C3588',
            'background_color_cassino' => '#0C3588',

            'search_border_color' => '#568CF7',
            'borders_and_dividers_colors' => '#568CF7'
            
        ],
        'red' => [

            'Border_bottons_and_selected' => '#FE3856',
            'bonus_color_dep' => '#FE3856',
            'color_players' => '#FE3856',
            'back_sub_color' => '#FE3856',
            'botao_deposito_background_nav' => '#FE3856',
            'botao_login_background_nav' => '#FE3856',
            'botao_login_background_modal' => '#FE3856',
            'botao_registro_background_modal' => '#FE3856',
            'botao_registro_border_nav' => '#FE3856',
            'botao_deposito_border_saq' => '#FE3856',
            'botao_deposito_background_dep' => '#FE3856',
            'botao_deposito_border_dep' => '#FE3856',
            'botao_deposito_background_saq' => '#FE3856',

            'search_back' => '#630B20',
            'placeholder_background' => '#630B20',
            'card_transaction' => '#630B20',
            'background_color_category' => '#630B20',
            'background_bottom_navigation' => '#630B20',
            'background_bottom_navigation_dark' => '#630B20',
            'footer_color' => '#630B20',
            'footer_color_dark' => '#630B20',
            'side_menu' => '#630B20',
            'side_menu_dark' => '#630B20',
            'navtop_color' => '#630B20',
            'navtop_color_dark' => '#630B20',

            'item_sub_color' => '#781830',
            'background_color_jackpot' => '#781830',
            'value_color_jackpot' => '#781830',
            'sidebar_color' => '#781830',
            'sidebar_color_dark' => '#781830',
            'background_base' => '#781830',
            'background_base_dark' => '#781830',
            'background_color_cassino' => '#781830',

            'search_border_color' => '#E08EA3',
            'borders_and_dividers_colors' => '#E08EA3'
                    
        ],
        'pink' => [

            'Border_bottons_and_selected' => '#99002B',
            'bonus_color_dep' => '#99002B',
            'color_players' => '#99002B',
            'back_sub_color' => '#99002B',
            'botao_deposito_background_nav' => '#99002B',
            'botao_login_background_nav' => '#99002B',
            'botao_login_background_modal' => '#99002B',
            'botao_registro_background_modal' => '#99002B',
            'botao_registro_border_nav' => '#99002B',
            'botao_deposito_border_saq' => '#99002B',
            'botao_deposito_background_dep' => '#99002B',
            'botao_deposito_border_dep' => '#99002B',
            'botao_deposito_background_saq' => '#99002B',

            'search_back' => '#C3607C',
            'placeholder_background' => '#C3607C',
            'card_transaction' => '#C3607C',
            'background_color_category' => '#C3607C',
            'background_bottom_navigation' => '#C3607C',
            'background_bottom_navigation_dark' => '#C3607C',
            'footer_color' => '#C3607C',
            'footer_color_dark' => '#C3607C',
            'side_menu' => '#C3607C',
            'side_menu_dark' => '#C3607C',
            'navtop_color' => '#C3607C',
            'navtop_color_dark' => '#C3607C',

            'item_sub_color' => '#D57490',
            'background_color_jackpot' => '#D57490',
            'value_color_jackpot' => '#D57490',
            'sidebar_color' => '#D57490',
            'sidebar_color_dark' => '#D57490',
            'background_base' => '#D57490',
            'background_base_dark' => '#D57490',
            'background_color_cassino' => '#D57490',

            'search_border_color' => '#E7BFCB',
            'borders_and_dividers_colors' => '#E7BFCB'
                     
        ],
        'limon' => [

            'Border_bottons_and_selected' => '#354505',
            'bonus_color_dep' => '#354505',
            'color_players' => '#354505',
            'back_sub_color' => '#354505',
            'botao_deposito_background_nav' => '#354505',
            'botao_login_background_nav' => '#354505',
            'botao_login_background_modal' => '#354505',
            'botao_registro_background_modal' => '#354505',
            'botao_registro_border_nav' => '#354505',
            'botao_deposito_border_saq' => '#354505',
            'botao_deposito_background_dep' => '#354505',
            'botao_deposito_border_dep' => '#354505',
            'botao_deposito_background_saq' => '#354505',

            'search_back' => '#5C780B',
            'placeholder_background' => '#5C780B',
            'card_transaction' => '#5C780B',
            'background_color_category' => '#5C780B',
            'background_bottom_navigation' => '#5C780B',
            'background_bottom_navigation_dark' => '#5C780B',
            'footer_color' => '#5C780B',
            'footer_color_dark' => '#5C780B',
            'side_menu' => '#5C780B',
            'side_menu_dark' => '#5C780B',
            'navtop_color' => '#5C780B',
            'navtop_color_dark' => '#5C780B',

            'item_sub_color' => '#8BA638',
            'background_color_jackpot' => '#8BA638',
            'value_color_jackpot' => '#8BA638',
            'sidebar_color' => '#8BA638',
            'sidebar_color_dark' => '#8BA638',
            'background_base' => '#8BA638',
            'background_base_dark' => '#8BA638',
            'background_color_cassino' => '#8BA638',

            'search_border_color' => '#F2FBB7',
            'borders_and_dividers_colors' => '#F2FBB7'
            
        ],
        'brown' => [

            'Border_bottons_and_selected' => '#FE3856',
            'bonus_color_dep' => '#FE3856',
            'color_players' => '#FE3856',
            'back_sub_color' => '#FE3856',
            'botao_deposito_background_nav' => '#FE3856',
            'botao_login_background_nav' => '#FE3856',
            'botao_login_background_modal' => '#FE3856',
            'botao_registro_background_modal' => '#FE3856',
            'botao_registro_border_nav' => '#FE3856',
            'botao_deposito_border_saq' => '#FE3856',
            'botao_deposito_background_dep' => '#FE3856',
            'botao_deposito_border_dep' => '#FE3856',
            'botao_deposito_background_saq' => '#FE3856',

            'search_back' => '#544038',
            'placeholder_background' => '#544038',
            'card_transaction' => '#544038',
            'background_color_category' => '#544038',
            'background_bottom_navigation' => '#544038',
            'background_bottom_navigation_dark' => '#544038',
            'footer_color' => '#544038',
            'footer_color_dark' => '#544038',
            'side_menu' => '#544038',
            'side_menu_dark' => '#544038',
            'navtop_color' => '#544038',
            'navtop_color_dark' => '#544038',

            'item_sub_color' => '#634C42',
            'background_color_jackpot' => '#634C42',
            'value_color_jackpot' => '#634C42',
            'sidebar_color' => '#634C42',
            'sidebar_color_dark' => '#634C42',
            'background_base' => '#634C42',
            'background_base_dark' => '#634C42',
            'background_color_cassino' => '#634C42',

            'search_border_color' => '#C1B7B3',
            'borders_and_dividers_colors' => '#C1B7B3'
                     
        ],
        'skyblue' => [

            'Border_bottons_and_selected' => '#EAB700',
            'bonus_color_dep' => '#EAB700',
            'color_players' => '#EAB700',
            'back_sub_color' => '#EAB700',
            'botao_deposito_background_nav' => '#EAB700',
            'botao_login_background_nav' => '#EAB700',
            'botao_login_background_modal' => '#EAB700',
            'botao_registro_background_modal' => '#EAB700',
            'botao_registro_border_nav' => '#EAB700',
            'botao_deposito_border_saq' => '#EAB700',
            'botao_deposito_background_dep' => '#EAB700',
            'botao_deposito_border_dep' => '#EAB700',
            'botao_deposito_background_saq' => '#EAB700',

            'search_back' => '#015ED4',
            'placeholder_background' => '#015ED4',
            'card_transaction' => '#015ED4',
            'background_color_category' => '#015ED4',
            'background_bottom_navigation' => '#015ED4',
            'background_bottom_navigation_dark' => '#015ED4',
            'footer_color' => '#015ED4',
            'footer_color_dark' => '#015ED4',
            'side_menu' => '#015ED4',
            'side_menu_dark' => '#015ED4',
            'navtop_color' => '#015ED4',
            'navtop_color_dark' => '#015ED4',

            'item_sub_color' => '#388AF0',
            'background_color_jackpot' => '#388AF0',
            'value_color_jackpot' => '#388AF0',
            'sidebar_color' => '#388AF0',
            'sidebar_color_dark' => '#388AF0',
            'background_base' => '#388AF0',
            'background_base_dark' => '#388AF0',
            'background_color_cassino' => '#388AF0',

            'search_border_color' => '#6DAFEE',
            'borders_and_dividers_colors' => '#6DAFEE'
                    
        ],
        'whiteblue' => [

            'Border_bottons_and_selected' => '#1F2B4D',
            'bonus_color_dep' => '#1F2B4D',
            'color_players' => '#1F2B4D',
            'back_sub_color' => '#1F2B4D',
            'botao_deposito_background_nav' => '#1F2B4D',
            'botao_login_background_nav' => '#1F2B4D',
            'botao_login_background_modal' => '#1F2B4D',
            'botao_registro_background_modal' => '#1F2B4D',
            'botao_registro_border_nav' => '#1F2B4D',
            'botao_deposito_border_saq' => '#1F2B4D',
            'botao_deposito_background_dep' => '#1F2B4D',
            'botao_deposito_border_dep' => '#1F2B4D',
            'botao_deposito_background_saq' => '#1F2B4D',

            'search_back' => '#5375D1',
            'placeholder_background' => '#5375D1',
            'card_transaction' => '#5375D1',
            'background_color_category' => '#5375D1',
            'background_bottom_navigation' => '#5375D1',
            'background_bottom_navigation_dark' => '#5375D1',
            'footer_color' => '#5375D1',
            'footer_color_dark' => '#5375D1',
            'side_menu' => '#5375D1',
            'side_menu_dark' => '#5375D1',
            'navtop_color' => '#5375D1',
            'navtop_color_dark' => '#5375D1',

            'item_sub_color' => '#8EABFA',
            'background_color_jackpot' => '#8EABFA',
            'value_color_jackpot' => '#8EABFA',
            'sidebar_color' => '#8EABFA',
            'sidebar_color_dark' => '#8EABFA',
            'background_base' => '#8EABFA',
            'background_base_dark' => '#8EABFA',
            'background_color_cassino' => '#8EABFA',

            'search_border_color' => '#BAC8ED',
            'borders_and_dividers_colors' => '#BAC8ED'
            
        ],
        'greendark' => [

            'Border_bottons_and_selected' => '#2FA33F',
            'bonus_color_dep' => '#2FA33F',
            'color_players' => '#2FA33F',
            'back_sub_color' => '#2FA33F',
            'botao_deposito_background_nav' => '#2FA33F',
            'botao_login_background_nav' => '#2FA33F',
            'botao_login_background_modal' => '#2FA33F',
            'botao_registro_background_modal' => '#2FA33F',
            'botao_registro_border_nav' => '#2FA33F',
            'botao_deposito_border_saq' => '#2FA33F',
            'botao_deposito_background_dep' => '#2FA33F',
            'botao_deposito_border_dep' => '#2FA33F',
            'botao_deposito_background_saq' => '#2FA33F',

            'search_back' => '#00352F',
            'placeholder_background' => '#00352F',
            'card_transaction' => '#00352F',
            'background_color_category' => '#00352F',
            'background_bottom_navigation' => '#00352F',
            'background_bottom_navigation_dark' => '#00352F',
            'footer_color' => '#00352F',
            'footer_color_dark' => '#00352F',
            'side_menu' => '#00352F',
            'side_menu_dark' => '#00352F',
            'navtop_color' => '#00352F',
            'navtop_color_dark' => '#00352F',

            'item_sub_color' => '#014D45',
            'background_color_jackpot' => '#014D45',
            'value_color_jackpot' => '#014D45',
            'sidebar_color' => '#014D45',
            'sidebar_color_dark' => '#014D45',
            'background_base' => '#014D45',
            'background_base_dark' => '#014D45',
            'background_color_cassino' => '#014D45',

            'search_border_color' => '#4FCABC',
            'borders_and_dividers_colors' => '#4FCABC'
                    
        ],
        'orange' => [

            'Border_bottons_and_selected' => '#551F0E',
            'bonus_color_dep' => '#551F0E',
            'color_players' => '#551F0E',
            'back_sub_color' => '#551F0E',
            'botao_deposito_background_nav' => '#551F0E',
            'botao_login_background_nav' => '#551F0E',
            'botao_login_background_modal' => '#551F0E',
            'botao_registro_background_modal' => '#551F0E',
            'botao_registro_border_nav' => '#551F0EF',
            'botao_deposito_border_saq' => '#551F0E',
            'botao_deposito_background_dep' => '#551F0E',
            'botao_deposito_border_dep' => '#551F0E',
            'botao_deposito_background_saq' => '#551F0E',

            'search_back' => '#F87607',
            'placeholder_background' => '#F87607',
            'card_transaction' => '#F87607',
            'background_color_category' => '#F87607',
            'background_bottom_navigation' => '#F87607',
            'background_bottom_navigation_dark' => '#F87607',
            'footer_color' => '#F87607',
            'footer_color_dark' => '#F87607',
            'side_menu' => '#F87607',
            'side_menu_dark' => '#F87607',
            'navtop_color' => '#F87607',
            'navtop_color_dark' => '#F87607',

            'item_sub_color' => '#F48E39',
            'background_color_jackpot' => '#F48E39',
            'value_color_jackpot' => '#F48E39',
            'sidebar_color' => '#F48E39',
            'sidebar_color_dark' => '#F48E39',
            'background_base' => '#F48E39',
            'background_base_dark' => '#F48E39',
            'background_color_cassino' => '#F48E39',

            'search_border_color' => '#FEE7CA',
            'borders_and_dividers_colors' => '#FEE7CA'
                   
        ],
        'green' => [

            'Border_bottons_and_selected' => '#EAB700',
            'bonus_color_dep' => '#EAB700',
            'color_players' => '#EAB700',
            'back_sub_color' => '#EAB700',
            'botao_deposito_background_nav' => '#EAB700',
            'botao_login_background_nav' => '#EAB700',
            'botao_login_background_modal' => '#EAB700',
            'botao_registro_background_modal' => '#EAB700',
            'botao_registro_border_nav' => '#EAB700',
            'botao_deposito_border_saq' => '#EAB700',
            'botao_deposito_background_dep' => '#EAB700',
            'botao_deposito_border_dep' => '#EAB700',
            'botao_deposito_background_saq' => '#EAB700',

            'search_back' => '#0D5E2B',
            'placeholder_background' => '#0D5E2B',
            'card_transaction' => '#0D5E2B',
            'background_color_category' => '#0D5E2B',
            'background_bottom_navigation' => '#0D5E2B',
            'background_bottom_navigation_dark' => '#0D5E2B',
            'footer_color' => '#0D5E2B',
            'footer_color_dark' => '#0D5E2B',
            'side_menu' => '#0D5E2B',
            'side_menu_dark' => '#0D5E2B',
            'navtop_color' => '#0D5E2B',
            'navtop_color_dark' => '#0D5E2B',

            'item_sub_color' => '#0C913F',
            'background_color_jackpot' => '#0C913F',
            'value_color_jackpot' => '#0C913F',
            'sidebar_color' => '#0C913F',
            'sidebar_color_dark' => '#0C913F',
            'background_base' => '#0C913F',
            'background_base_dark' => '#0C913F',
            'background_color_cassino' => '#0C913F',

            'search_border_color' => '#7BD39B',
            'borders_and_dividers_colors' => '#7BD39B'
            
        ],
        'yellow' => [

            'Border_bottons_and_selected' => '#373638',
            'bonus_color_dep' => '#373638',
            'color_players' => '#373638',
            'back_sub_color' => '#373638',
            'botao_deposito_background_nav' => '#373638',
            'botao_login_background_nav' => '#373638',
            'botao_login_background_modal' => '#373638',
            'botao_registro_background_modal' => '#373638',
            'botao_registro_border_nav' => '#373638',
            'botao_deposito_border_saq' => '#373638',
            'botao_deposito_background_dep' => '#373638',
            'botao_deposito_border_dep' => '#373638',
            'botao_deposito_background_saq' => '#373638',

            'search_back' => '#F2A200',
            'placeholder_background' => '#F2A200',
            'card_transaction' => '#F2A200',
            'background_color_category' => '#F2A200',
            'background_bottom_navigation' => '#F2A200',
            'background_bottom_navigation_dark' => '#F2A200',
            'footer_color' => '#F2A200',
            'footer_color_dark' => '#F2A200',
            'side_menu' => '#F2A200',
            'side_menu_dark' => '#F2A200',
            'navtop_color' => '#F2A200',
            'navtop_color_dark' => '#F2A200',

            'item_sub_color' => '#FDD155',
            'background_color_jackpot' => '#FDD155',
            'value_color_jackpot' => '#FDD155',
            'sidebar_color' => '#FDD155',
            'sidebar_color_dark' => '#FDD155',
            'background_base' => '#FDD155',
            'background_base_dark' => '#FDD155',
            'background_color_cassino' => '#FDD155',

            'search_border_color' => '#FEE8A8',
            'borders_and_dividers_colors' => '#FEE8A8'
            
        ],
        'greenwhite' => [

            'Border_bottons_and_selected' => '#0F4D3B',
            'bonus_color_dep' => '#0F4D3B',
            'color_players' => '#0F4D3B',
            'back_sub_color' => '#0F4D3B',
            'botao_deposito_background_nav' => '#0F4D3B',
            'botao_login_background_nav' => '#0F4D3B',
            'botao_login_background_modal' => '#0F4D3B',
            'botao_registro_background_modal' => '#0F4D3B',
            'botao_registro_border_nav' => '#0F4D3B',
            'botao_deposito_border_saq' => '#0F4D3B',
            'botao_deposito_background_dep' => '#0F4D3B',
            'botao_deposito_border_dep' => '#0F4D3B',
            'botao_deposito_background_saq' => '#0F4D3B',

            'search_back' => '#21A57D',
            'placeholder_background' => '#21A57D',
            'card_transaction' => '#21A57D',
            'background_color_category' => '#21A57D',
            'background_bottom_navigation' => '#21A57D',
            'background_bottom_navigation_dark' => '#21A57D',
            'footer_color' => '#21A57D',
            'footer_color_dark' => '#21A57D',
            'side_menu' => '#21A57D',
            'side_menu_dark' => '#21A57D',
            'navtop_color' => '#21A57D',
            'navtop_color_dark' => '#21A57D',

            'item_sub_color' => '#4EBB95',
            'background_color_jackpot' => '#4EBB95',
            'value_color_jackpot' => '#4EBB95',
            'sidebar_color' => '#4EBB95',
            'sidebar_color_dark' => '#4EBB95',
            'background_base' => '#4EBB95',
            'background_base_dark' => '#4EBB95',
            'background_color_cassino' => '#4EBB95',

            'search_border_color' => '#89F1CD',
            'borders_and_dividers_colors' => '#89F1CD'
            
        ],
        'gray' => [

            'Border_bottons_and_selected' => '#373638',
            'bonus_color_dep' => '#373638',
            'color_players' => '#373638',
            'back_sub_color' => '#373638',
            'botao_deposito_background_nav' => '#373638',
            'botao_login_background_nav' => '#373638',
            'botao_login_background_modal' => '#373638',
            'botao_registro_background_modal' => '#373638',
            'botao_registro_border_nav' => '#373638',
            'botao_deposito_border_saq' => '#373638',
            'botao_deposito_background_dep' => '#373638',
            'botao_deposito_border_dep' => '#373638',
            'botao_deposito_background_saq' => '#373638',

            'search_back' => '#648872',
            'placeholder_background' => '#648872',
            'card_transaction' => '#648872',
            'background_color_category' => '#648872',
            'background_bottom_navigation' => '#648872',
            'background_bottom_navigation_dark' => '#648872',
            'footer_color' => '#648872',
            'footer_color_dark' => '#648872',
            'side_menu' => '#648872',
            'side_menu_dark' => '#648872',
            'navtop_color' => '#648872',
            'navtop_color_dark' => '#648872',

            'item_sub_color' => '#799B86',
            'background_color_jackpot' => '#799B86',
            'value_color_jackpot' => '#799B86',
            'sidebar_color' => '#799B86',
            'sidebar_color_dark' => '#799B86',
            'background_base' => '#799B86',
            'background_base_dark' => '#799B86',
            'background_color_cassino' => '#799B86',

            'search_border_color' => '#A0D3B3',
            'borders_and_dividers_colors' => '#A0D3B3'
            
        ],

    ];

    if (array_key_exists($theme, $themes)) {
        $themeData = $themes[$theme];

        // Atualize o banco de dados com os valores do tema escolhido
        \DB::table('custom_layouts')->update([

            'Border_bottons_and_selected' => $themeData['Border_bottons_and_selected'],
            'bonus_color_dep' => $themeData['bonus_color_dep'],
            'color_players' => $themeData['color_players'],
            'back_sub_color' => $themeData['back_sub_color'],
            'botao_deposito_background_nav' => $themeData['botao_deposito_background_nav'],
            'botao_login_background_nav' => $themeData['botao_login_background_nav'],
            'botao_login_background_modal' => $themeData['botao_login_background_modal'],
            'botao_registro_background_modal' => $themeData['botao_registro_background_modal'],
            'botao_registro_border_nav' => $themeData['botao_registro_border_nav'],
            'botao_deposito_border_saq' => $themeData['botao_deposito_border_saq'],
            'botao_deposito_background_dep' => $themeData['botao_deposito_background_dep'],
            'botao_deposito_border_dep' => $themeData['botao_deposito_border_dep'],
            'botao_deposito_background_saq' => $themeData['botao_deposito_background_saq'],

            'search_back' => $themeData['search_back'],
            'placeholder_background' => $themeData['placeholder_background'],
            'card_transaction' => $themeData['card_transaction'],
            'background_color_category' => $themeData['background_color_category'],
            'background_bottom_navigation' => $themeData['background_bottom_navigation'],
            'background_bottom_navigation_dark' => $themeData['background_bottom_navigation_dark'],
            'footer_color' => $themeData['footer_color'],
            'footer_color_dark' => $themeData['footer_color_dark'],
            'side_menu' => $themeData['side_menu'],
            'side_menu_dark' => $themeData['side_menu_dark'],
            'navtop_color' => $themeData['navtop_color'],
            'navtop_color_dark' => $themeData['navtop_color_dark'],

            'item_sub_color' => $themeData['item_sub_color'],
            'background_color_jackpot' => $themeData['background_color_jackpot'],
            'value_color_jackpot' => $themeData['value_color_jackpot'],
            'sidebar_color' => $themeData['sidebar_color'],
            'sidebar_color_dark' => $themeData['sidebar_color_dark'],
            'background_base' => $themeData['background_base'],
            'background_base_dark' => $themeData['background_base_dark'],
            'background_color_cassino' => $themeData['background_color_cassino'],

            'search_border_color' => $themeData['search_border_color'],
            'borders_and_dividers_colors' => $themeData['borders_and_dividers_colors'],                  

        ]);

        return true;
    }

    return false;
}
}

return [
    'themes' => [
        'pourple' => 'Pourple',
        'black' => 'Black',
        'blue' => 'Blue',
        'red' => 'Red',
        'pink' => 'Pink',
        'limon' => 'Pimon',
        'brown' => 'Brown',
        'skyblue' => 'Skyblue',
        'whiteblue' => 'Whiteblue',
        'greendark' => 'Greendark',
        'orange' => 'Orange',
        'green' => 'Green',
        'yellow' => 'Yellow',
        'greenwhite' => 'Greenwhite',
        'gray' => 'Gray',
    ],
];