<?php

if (!function_exists('applyTheme')) {
    function applyTheme($theme)
    {
        $themes = [
        'pourple' => [            
            'Border_bottons_and_selected' => '#291F40',
            'bonus_color_dep' => '#291F40',
            'color_players' => '#291F40',
            'back_sub_color' => '#291F40',
            'botao_deposito_background_nav' => '#291F40',
            'botao_login_background_nav' => '#291F40',
            'botao_login_background_modal' => '#291F40',
            'botao_registro_background_modal' => '#291F40',
            'botao_registro_border_nav' => '#291F40',
            'botao_deposito_border_saq' => '#291F40',
            'botao_deposito_background_dep' => '#291F40',
            'botao_deposito_border_dep' => '#291F40',
            'botao_deposito_background_saq' => '#291F40',

            'search_back' => '#58418C',
            'placeholder_background' => '#58418C',
            'card_transaction' => '#58418C',
            'background_color_category' => '#58418C',
            'background_bottom_navigation' => '#58418C',
            'background_bottom_navigation_dark' => '#58418C',
            'footer_color' => '#58418C',
            'footer_color_dark' => '#58418C',
            'side_menu' => '#58418C',
            'side_menu_dark' => '#58418C',
            'navtop_color' => '#58418C',
            'navtop_color_dark' => '#58418C',

            'item_sub_color' => '#6B53A2',
            'background_color_jackpot' => '#6B53A2',
            'value_color_jackpot' => '#6B53A2',
            'sidebar_color' => '#6B53A2',
            'sidebar_color_dark' => '#6B53A2',
            'background_base' => '#6B53A2',
            'background_base_dark' => '#6B53A2',
            'background_color_cassino' => '#6B53A2',

            'search_border_color' => '#8870B8',
            'borders_and_dividers_colors' => '#8870B8'                       
        ],

        'black' => [

            'Border_bottons_and_selected' => '#2FA33F',
            'bonus_color_dep' => '#2FA33F',
            'color_players' => '#2FA33F',
            'back_sub_color' => '#2FA33F',
            'botao_deposito_background_nav' => '#2FA33F',
            'botao_login_background_nav' => '#2FA33F',
            'botao_login_background_modal' => '#2FA33F',
            'botao_registro_background_modal' => '#2FA33F',
            'botao_registro_border_nav' => '#2FA33F',
            'botao_deposito_border_saq' => '#2FA33F',
            'botao_deposito_background_dep' => '#2FA33F',
            'botao_deposito_border_dep' => '#2FA33F',
            'botao_deposito_background_saq' => '#2FA33F',

            'search_back' => '#161D29',
            'placeholder_background' => '#161D29',
            'card_transaction' => '#161D29',
            'background_color_category' => '#161D29',
            'background_bottom_navigation' => '#161D29',
            'background_bottom_navigation_dark' => '#161D29',
            'footer_color' => '#161D29',
            'footer_color_dark' => '#161D29',
            'side_menu' => '#161D29',
            'side_menu_dark' => '#161D29',
            'navtop_color' => '#161D29',
            'navtop_color_dark' => '#161D29',

            'item_sub_color' => '#0D131C',
            'background_color_jackpot' => '#0D131C',
            'value_color_jackpot' => '#0D131C',
            'sidebar_color' => '#0D131C',
            'sidebar_color_dark' => '#0D131C',
            'background_base' => '#0D131C',
            'background_base_dark' => '#0D131C',
            'background_color_cassino' => '#0D131C',

            'search_border_color' => '#6D7A91',
            'borders_and_dividers_colors' => '#6D7A91'  

        ],
        'blue' => [

            'Border_bottons_and_selected' => '#2FA33F',
            'bonus_color_dep' => '#2FA33F',
            'color_players' => '#2FA33F',
            'back_sub_color' => '#2FA33F',
            'botao_deposito_background_nav' => '#2FA33F',
            'botao_login_background_nav' => '#2FA33F',
            'botao_login_background_modal' => '#2FA33F',
            'botao_registro_background_modal' => '#2FA33F',
            'botao_registro_border_nav' => '#2FA33F',
            'botao_deposito_border_saq' => '#2FA33F',
            'botao_deposito_background_dep' => '#2FA33F',
            'botao_deposito_border_dep' => '#2FA33F',
            'botao_deposito_background_saq' => '#2FA33F',

            'search_back' => '#092C71',
            'placeholder_background' => '#092C71',
            'card_transaction' => '#092C71',
            'background_color_category' => '#092C71',
            'background_bottom_navigation' => '#092C71',
            'background_bottom_navigation_dark' => '#092C71',
            'footer_color' => '#092C71',
            'footer_color_dark' => '#092C71',
            'side_menu' => '#092C71',
            'side_menu_dark' => '#092C71',
            'navtop_color' => '#092C71',
            'navtop_color_dark' => '#092C71',

            'item_sub_color' => '#0C3588',
            'background_color_jackpot' => '#0C3588',
            'value_color_jackpot' => '#0C3588',
            'sidebar_color' => '#0C3588',
            'sidebar_color_dark' => '#0C3588',
            'background_base' => '#0C3588',
            'background_base_dark' => '#0C3588',
            'background_color_cassino' => '#0C3588',

            'search_border_color' => '#568CF7',
            'borders_and_dividers_colors' => '#568CF7'
            
        ],
        'red' => [

            'Border_bottons_and_selected' => '#FE3856',
            'bonus_color_dep' => '#FE3856',
            'color_players' => '#FE3856',
            'back_sub_color' => '#FE3856',
            'botao_deposito_background_nav' => '#FE3856',
            'botao_login_background_nav' => '#FE3856',
            'botao_login_background_modal' => '#FE3856',
            'botao_registro_background_modal' => '#FE3856',
            'botao_registro_border_nav' => '#FE3856',
            'botao_deposito_border_saq' => '#FE3856',
            'botao_deposito_background_dep' => '#FE3856',
            'botao_deposito_border_dep' => '#FE3856',
            'botao_deposito_background_saq' => '#FE3856',

            'search_back' => '#630B20',
            'placeholder_background' => '#630B20',
            'card_transaction' => '#630B20',
            'background_color_category' => '#630B20',
            'background_bottom_navigation' => '#630B20',
            'background_bottom_navigation_dark' => '#630B20',
            'footer_color' => '#630B20',
            'footer_color_dark' => '#630B20',
            'side_menu' => '#630B20',
            'side_menu_dark' => '#630B20',
            'navtop_color' => '#630B20',
            'navtop_color_dark' => '#630B20',

            'item_sub_color' => '#781830',
            'background_color_jackpot' => '#781830',
            'value_color_jackpot' => '#781830',
            'sidebar_color' => '#781830',
            'sidebar_color_dark' => '#781830',
            'background_base' => '#781830',
            'background_base_dark' => '#781830',
            'background_color_cassino' => '#781830',

            'search_border_color' => '#E08EA3',
            'borders_and_dividers_colors' => '#E08EA3'
                    
        ],
        'pink' => [

            'Border_bottons_and_selected' => '#99002B',
            'bonus_color_dep' => '#99002B',
            'color_players' => '#99002B',
            'back_sub_color' => '#99002B',
            'botao_deposito_background_nav' => '#99002B',
            'botao_login_background_nav' => '#99002B',
            'botao_login_background_modal' => '#99002B',
            'botao_registro_background_modal' => '#99002B',
            'botao_registro_border_nav' => '#99002B',
            'botao_deposito_border_saq' => '#99002B',
            'botao_deposito_background_dep' => '#99002B',
            'botao_deposito_border_dep' => '#99002B',
            'botao_deposito_background_saq' => '#99002B',

            'search_back' => '#C3607C',
            'placeholder_background' => '#C3607C',
            'card_transaction' => '#C3607C',
            'background_color_category' => '#C3607C',
            'background_bottom_navigation' => '#C3607C',
            'background_bottom_navigation_dark' => '#C3607C',
            'footer_color' => '#C3607C',
            'footer_color_dark' => '#C3607C',
            'side_menu' => '#C3607C',
            'side_menu_dark' => '#C3607C',
            'navtop_color' => '#C3607C',
            'navtop_color_dark' => '#C3607C',

            'item_sub_color' => '#D57490',
            'background_color_jackpot' => '#D57490',
            'value_color_jackpot' => '#D57490',
            'sidebar_color' => '#D57490',
            'sidebar_color_dark' => '#D57490',
            'background_base' => '#D57490',
            'background_base_dark' => '#D57490',
            'background_color_cassino' => '#D57490',

            'search_border_color' => '#E7BFCB',
            'borders_and_dividers_colors' => '#E7BFCB'
                     
        ],
        'limon' => [

            'Border_bottons_and_selected' => '#354505',
            'bonus_color_dep' => '#354505',
            'color_players' => '#354505',
            'back_sub_color' => '#354505',
            'botao_deposito_background_nav' => '#354505',
            'botao_login_background_nav' => '#354505',
            'botao_login_background_modal' => '#354505',
            'botao_registro_background_modal' => '#354505',
            'botao_registro_border_nav' => '#354505',
            'botao_deposito_border_saq' => '#354505',
            'botao_deposito_background_dep' => '#354505',
            'botao_deposito_border_dep' => '#354505',
            'botao_deposito_background_saq' => '#354505',

            'search_back' => '#5C780B',
            'placeholder_background' => '#5C780B',
            'card_transaction' => '#5C780B',
            'background_color_category' => '#5C780B',
            'background_bottom_navigation' => '#5C780B',
            'background_bottom_navigation_dark' => '#5C780B',
            'footer_color' => '#5C780B',
            'footer_color_dark' => '#5C780B',
            'side_menu' => '#5C780B',
            'side_menu_dark' => '#5C780B',
            'navtop_color' => '#5C780B',
            'navtop_color_dark' => '#5C780B',

            'item_sub_color' => '#8BA638',
            'background_color_jackpot' => '#8BA638',
            'value_color_jackpot' => '#8BA638',
            'sidebar_color' => '#8BA638',
            'sidebar_color_dark' => '#8BA638',
            'background_base' => '#8BA638',
            'background_base_dark' => '#8BA638',
            'background_color_cassino' => '#8BA638',

            'search_border_color' => '#F2FBB7',
            'borders_and_dividers_colors' => '#F2FBB7'
            
        ],
        'brown' => [

            'Border_bottons_and_selected' => '#FE3856',
            'bonus_color_dep' => '#FE3856',
            'color_players' => '#FE3856',
            'back_sub_color' => '#FE3856',
            'botao_deposito_background_nav' => '#FE3856',
            'botao_login_background_nav' => '#FE3856',
            'botao_login_background_modal' => '#FE3856',
            'botao_registro_background_modal' => '#FE3856',
            'botao_registro_border_nav' => '#FE3856',
            'botao_deposito_border_saq' => '#FE3856',
            'botao_deposito_background_dep' => '#FE3856',
            'botao_deposito_border_dep' => '#FE3856',
            'botao_deposito_background_saq' => '#FE3856',

            'search_back' => '#544038',
            'placeholder_background' => '#544038',
            'card_transaction' => '#544038',
            'background_color_category' => '#544038',
            'background_bottom_navigation' => '#544038',
            'background_bottom_navigation_dark' => '#544038',
            'footer_color' => '#544038',
            'footer_color_dark' => '#544038',
            'side_menu' => '#544038',
            'side_menu_dark' => '#544038',
            'navtop_color' => '#544038',
            'navtop_color_dark' => '#544038',

            'item_sub_color' => '#634C42',
            'background_color_jackpot' => '#634C42',
            'value_color_jackpot' => '#634C42',
            'sidebar_color' => '#634C42',
            'sidebar_color_dark' => '#634C42',
            'background_base' => '#634C42',
            'background_base_dark' => '#634C42',
            'background_color_cassino' => '#634C42',

            'search_border_color' => '#C1B7B3',
            'borders_and_dividers_colors' => '#C1B7B3'
                     
        ],
        'skyblue' => [

            'Border_bottons_and_selected' => '#EAB700',
            'bonus_color_dep' => '#EAB700',
            'color_players' => '#EAB700',
            'back_sub_color' => '#EAB700',
            'botao_deposito_background_nav' => '#EAB700',
            'botao_login_background_nav' => '#EAB700',
            'botao_login_background_modal' => '#EAB700',
            'botao_registro_background_modal' => '#EAB700',
            'botao_registro_border_nav' => '#EAB700',
            'botao_deposito_border_saq' => '#EAB700',
            'botao_deposito_background_dep' => '#EAB700',
            'botao_deposito_border_dep' => '#EAB700',
            'botao_deposito_background_saq' => '#EAB700',

            'search_back' => '#015ED4',
            'placeholder_background' => '#015ED4',
            'card_transaction' => '#015ED4',
            'background_color_category' => '#015ED4',
            'background_bottom_navigation' => '#015ED4',
            'background_bottom_navigation_dark' => '#015ED4',
            'footer_color' => '#015ED4',
            'footer_color_dark' => '#015ED4',
            'side_menu' => '#015ED4',
            'side_menu_dark' => '#015ED4',
            'navtop_color' => '#015ED4',
            'navtop_color_dark' => '#015ED4',

            'item_sub_color' => '#388AF0',
            'background_color_jackpot' => '#388AF0',
            'value_color_jackpot' => '#388AF0',
            'sidebar_color' => '#388AF0',
            'sidebar_color_dark' => '#388AF0',
            'background_base' => '#388AF0',
            'background_base_dark' => '#388AF0',
            'background_color_cassino' => '#388AF0',

            'search_border_color' => '#6DAFEE',
            'borders_and_dividers_colors' => '#6DAFEE'
                    
        ],
        'whiteblue' => [

            'Border_bottons_and_selected' => '#1F2B4D',
            'bonus_color_dep' => '#1F2B4D',
            'color_players' => '#1F2B4D',
            'back_sub_color' => '#1F2B4D',
            'botao_deposito_background_nav' => '#1F2B4D',
            'botao_login_background_nav' => '#1F2B4D',
            'botao_login_background_modal' => '#1F2B4D',
            'botao_registro_background_modal' => '#1F2B4D',
            'botao_registro_border_nav' => '#1F2B4D',
            'botao_deposito_border_saq' => '#1F2B4D',
            'botao_deposito_background_dep' => '#1F2B4D',
            'botao_deposito_border_dep' => '#1F2B4D',
            'botao_deposito_background_saq' => '#1F2B4D',

            'search_back' => '#5375D1',
            'placeholder_background' => '#5375D1',
            'card_transaction' => '#5375D1',
            'background_color_category' => '#5375D1',
            'background_bottom_navigation' => '#5375D1',
            'background_bottom_navigation_dark' => '#5375D1',
            'footer_color' => '#5375D1',
            'footer_color_dark' => '#5375D1',
            'side_menu' => '#5375D1',
            'side_menu_dark' => '#5375D1',
            'navtop_color' => '#5375D1',
            'navtop_color_dark' => '#5375D1',

            'item_sub_color' => '#8EABFA',
            'background_color_jackpot' => '#8EABFA',
            'value_color_jackpot' => '#8EABFA',
            'sidebar_color' => '#8EABFA',
            'sidebar_color_dark' => '#8EABFA',
            'background_base' => '#8EABFA',
            'background_base_dark' => '#8EABFA',
            'background_color_cassino' => '#8EABFA',

            'search_border_color' => '#BAC8ED',
            'borders_and_dividers_colors' => '#BAC8ED'
            
        ],
        'greendark' => [

            'Border_bottons_and_selected' => '#2FA33F',
            'bonus_color_dep' => '#2FA33F',
            'color_players' => '#2FA33F',
            'back_sub_color' => '#2FA33F',
            'botao_deposito_background_nav' => '#2FA33F',
            'botao_login_background_nav' => '#2FA33F',
            'botao_login_background_modal' => '#2FA33F',
            'botao_registro_background_modal' => '#2FA33F',
            'botao_registro_border_nav' => '#2FA33F',
            'botao_deposito_border_saq' => '#2FA33F',
            'botao_deposito_background_dep' => '#2FA33F',
            'botao_deposito_border_dep' => '#2FA33F',
            'botao_deposito_background_saq' => '#2FA33F',

            'search_back' => '#00352F',
            'placeholder_background' => '#00352F',
            'card_transaction' => '#00352F',
            'background_color_category' => '#00352F',
            'background_bottom_navigation' => '#00352F',
            'background_bottom_navigation_dark' => '#00352F',
            'footer_color' => '#00352F',
            'footer_color_dark' => '#00352F',
            'side_menu' => '#00352F',
            'side_menu_dark' => '#00352F',
            'navtop_color' => '#00352F',
            'navtop_color_dark' => '#00352F',

            'item_sub_color' => '#014D45',
            'background_color_jackpot' => '#014D45',
            'value_color_jackpot' => '#014D45',
            'sidebar_color' => '#014D45',
            'sidebar_color_dark' => '#014D45',
            'background_base' => '#014D45',
            'background_base_dark' => '#014D45',
            'background_color_cassino' => '#014D45',

            'search_border_color' => '#4FCABC',
            'borders_and_dividers_colors' => '#4FCABC'
                    
        ],
        'orange' => [

            'Border_bottons_and_selected' => '#551F0E',
            'bonus_color_dep' => '#551F0E',
            'color_players' => '#551F0E',
            'back_sub_color' => '#551F0E',
            'botao_deposito_background_nav' => '#551F0E',
            'botao_login_background_nav' => '#551F0E',
            'botao_login_background_modal' => '#551F0E',
            'botao_registro_background_modal' => '#551F0E',
            'botao_registro_border_nav' => '#551F0EF',
            'botao_deposito_border_saq' => '#551F0E',
            'botao_deposito_background_dep' => '#551F0E',
            'botao_deposito_border_dep' => '#551F0E',
            'botao_deposito_background_saq' => '#551F0E',

            'search_back' => '#F87607',
            'placeholder_background' => '#F87607',
            'card_transaction' => '#F87607',
            'background_color_category' => '#F87607',
            'background_bottom_navigation' => '#F87607',
            'background_bottom_navigation_dark' => '#F87607',
            'footer_color' => '#F87607',
            'footer_color_dark' => '#F87607',
            'side_menu' => '#F87607',
            'side_menu_dark' => '#F87607',
            'navtop_color' => '#F87607',
            'navtop_color_dark' => '#F87607',

            'item_sub_color' => '#F48E39',
            'background_color_jackpot' => '#F48E39',
            'value_color_jackpot' => '#F48E39',
            'sidebar_color' => '#F48E39',
            'sidebar_color_dark' => '#F48E39',
            'background_base' => '#F48E39',
            'background_base_dark' => '#F48E39',
            'background_color_cassino' => '#F48E39',

            'search_border_color' => '#FEE7CA',
            'borders_and_dividers_colors' => '#FEE7CA'
                   
        ],
        'green' => [

            'Border_bottons_and_selected' => '#EAB700',
            'bonus_color_dep' => '#EAB700',
            'color_players' => '#EAB700',
            'back_sub_color' => '#EAB700',
            'botao_deposito_background_nav' => '#EAB700',
            'botao_login_background_nav' => '#EAB700',
            'botao_login_background_modal' => '#EAB700',
            'botao_registro_background_modal' => '#EAB700',
            'botao_registro_border_nav' => '#EAB700',
            'botao_deposito_border_saq' => '#EAB700',
            'botao_deposito_background_dep' => '#EAB700',
            'botao_deposito_border_dep' => '#EAB700',
            'botao_deposito_background_saq' => '#EAB700',

            'search_back' => '#0D5E2B',
            'placeholder_background' => '#0D5E2B',
            'card_transaction' => '#0D5E2B',
            'background_color_category' => '#0D5E2B',
            'background_bottom_navigation' => '#0D5E2B',
            'background_bottom_navigation_dark' => '#0D5E2B',
            'footer_color' => '#0D5E2B',
            'footer_color_dark' => '#0D5E2B',
            'side_menu' => '#0D5E2B',
            'side_menu_dark' => '#0D5E2B',
            'navtop_color' => '#0D5E2B',
            'navtop_color_dark' => '#0D5E2B',

            'item_sub_color' => '#0C913F',
            'background_color_jackpot' => '#0C913F',
            'value_color_jackpot' => '#0C913F',
            'sidebar_color' => '#0C913F',
            'sidebar_color_dark' => '#0C913F',
            'background_base' => '#0C913F',
            'background_base_dark' => '#0C913F',
            'background_color_cassino' => '#0C913F',

            'search_border_color' => '#7BD39B',
            'borders_and_dividers_colors' => '#7BD39B'
            
        ],
        'yellow' => [

            'Border_bottons_and_selected' => '#373638',
            'bonus_color_dep' => '#373638',
            'color_players' => '#373638',
            'back_sub_color' => '#373638',
            'botao_deposito_background_nav' => '#373638',
            'botao_login_background_nav' => '#373638',
            'botao_login_background_modal' => '#373638',
            'botao_registro_background_modal' => '#373638',
            'botao_registro_border_nav' => '#373638',
            'botao_deposito_border_saq' => '#373638',
            'botao_deposito_background_dep' => '#373638',
            'botao_deposito_border_dep' => '#373638',
            'botao_deposito_background_saq' => '#373638',

            'search_back' => '#F2A200',
            'placeholder_background' => '#F2A200',
            'card_transaction' => '#F2A200',
            'background_color_category' => '#F2A200',
            'background_bottom_navigation' => '#F2A200',
            'background_bottom_navigation_dark' => '#F2A200',
            'footer_color' => '#F2A200',
            'footer_color_dark' => '#F2A200',
            'side_menu' => '#F2A200',
            'side_menu_dark' => '#F2A200',
            'navtop_color' => '#F2A200',
            'navtop_color_dark' => '#F2A200',

            'item_sub_color' => '#FDD155',
            'background_color_jackpot' => '#FDD155',
            'value_color_jackpot' => '#FDD155',
            'sidebar_color' => '#FDD155',
            'sidebar_color_dark' => '#FDD155',
            'background_base' => '#FDD155',
            'background_base_dark' => '#FDD155',
            'background_color_cassino' => '#FDD155',

            'search_border_color' => '#FEE8A8',
            'borders_and_dividers_colors' => '#FEE8A8'
            
        ],
        'greenwhite' => [

            'Border_bottons_and_selected' => '#0F4D3B',
            'bonus_color_dep' => '#0F4D3B',
            'color_players' => '#0F4D3B',
            'back_sub_color' => '#0F4D3B',
            'botao_deposito_background_nav' => '#0F4D3B',
            'botao_login_background_nav' => '#0F4D3B',
            'botao_login_background_modal' => '#0F4D3B',
            'botao_registro_background_modal' => '#0F4D3B',
            'botao_registro_border_nav' => '#0F4D3B',
            'botao_deposito_border_saq' => '#0F4D3B',
            'botao_deposito_background_dep' => '#0F4D3B',
            'botao_deposito_border_dep' => '#0F4D3B',
            'botao_deposito_background_saq' => '#0F4D3B',

            'search_back' => '#21A57D',
            'placeholder_background' => '#21A57D',
            'card_transaction' => '#21A57D',
            'background_color_category' => '#21A57D',
            'background_bottom_navigation' => '#21A57D',
            'background_bottom_navigation_dark' => '#21A57D',
            'footer_color' => '#21A57D',
            'footer_color_dark' => '#21A57D',
            'side_menu' => '#21A57D',
            'side_menu_dark' => '#21A57D',
            'navtop_color' => '#21A57D',
            'navtop_color_dark' => '#21A57D',

            'item_sub_color' => '#4EBB95',
            'background_color_jackpot' => '#4EBB95',
            'value_color_jackpot' => '#4EBB95',
            'sidebar_color' => '#4EBB95',
            'sidebar_color_dark' => '#4EBB95',
            'background_base' => '#4EBB95',
            'background_base_dark' => '#4EBB95',
            'background_color_cassino' => '#4EBB95',

            'search_border_color' => '#89F1CD',
            'borders_and_dividers_colors' => '#89F1CD'
            
        ],
        'gray' => [

            'Border_bottons_and_selected' => '#373638',
            'bonus_color_dep' => '#373638',
            'color_players' => '#373638',
            'back_sub_color' => '#373638',
            'botao_deposito_background_nav' => '#373638',
            'botao_login_background_nav' => '#373638',
            'botao_login_background_modal' => '#373638',
            'botao_registro_background_modal' => '#373638',
            'botao_registro_border_nav' => '#373638',
            'botao_deposito_border_saq' => '#373638',
            'botao_deposito_background_dep' => '#373638',
            'botao_deposito_border_dep' => '#373638',
            'botao_deposito_background_saq' => '#373638',

            'search_back' => '#648872',
            'placeholder_background' => '#648872',
            'card_transaction' => '#648872',
            'background_color_category' => '#648872',
            'background_bottom_navigation' => '#648872',
            'background_bottom_navigation_dark' => '#648872',
            'footer_color' => '#648872',
            'footer_color_dark' => '#648872',
            'side_menu' => '#648872',
            'side_menu_dark' => '#648872',
            'navtop_color' => '#648872',
            'navtop_color_dark' => '#648872',

            'item_sub_color' => '#799B86',
            'background_color_jackpot' => '#799B86',
            'value_color_jackpot' => '#799B86',
            'sidebar_color' => '#799B86',
            'sidebar_color_dark' => '#799B86',
            'background_base' => '#799B86',
            'background_base_dark' => '#799B86',
            'background_color_cassino' => '#799B86',

            'search_border_color' => '#A0D3B3',
            'borders_and_dividers_colors' => '#A0D3B3'
            
        ],
        'violet' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#8A2BE2',
            'bonus_color_dep'               => '#8A2BE2',
            'color_players'                 => '#8A2BE2',
            'back_sub_color'                => '#8A2BE2',
            'botao_deposito_background_nav' => '#8A2BE2',
            'botao_login_background_nav'    => '#8A2BE2',
            'botao_login_background_modal'  => '#8A2BE2',
            'botao_registro_background_modal'=> '#8A2BE2',
            'botao_registro_border_nav'     => '#8A2BE2',
            'botao_deposito_border_saq'     => '#8A2BE2',
            'botao_deposito_background_dep'=> '#8A2BE2',
            'botao_deposito_border_dep'     => '#8A2BE2',
            'botao_deposito_background_saq'=> '#8A2BE2',
    
            // Grupo Secundário
            'search_back'                   => '#9370DB',
            'placeholder_background'        => '#9370DB',
            'card_transaction'              => '#9370DB',
            'background_color_category'     => '#9370DB',
            'background_bottom_navigation'  => '#9370DB',
            'background_bottom_navigation_dark' => '#9370DB',
            'footer_color'                  => '#9370DB',
            'footer_color_dark'             => '#9370DB',
            'side_menu'                     => '#9370DB',
            'side_menu_dark'                => '#9370DB',
            'navtop_color'                  => '#9370DB',
            'navtop_color_dark'             => '#9370DB',
    
            // Grupo Terciário
            'item_sub_color'                => '#7B68EE',
            'background_color_jackpot'      => '#7B68EE',
            'value_color_jackpot'           => '#7B68EE',
            'sidebar_color'                 => '#7B68EE',
            'sidebar_color_dark'            => '#7B68EE',
            'background_base'               => '#7B68EE',
            'background_base_dark'          => '#7B68EE',
            'background_color_cassino'      => '#7B68EE',
    
            // Grupo Quaternário
            'search_border_color'           => '#6A5ACD',
            'borders_and_dividers_colors'   => '#6A5ACD',
        ],
    
        'aqua' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#00FFFF',
            'bonus_color_dep'               => '#00FFFF',
            'color_players'                 => '#00FFFF',
            'back_sub_color'                => '#00FFFF',
            'botao_deposito_background_nav' => '#00FFFF',
            'botao_login_background_nav'    => '#00FFFF',
            'botao_login_background_modal'  => '#00FFFF',
            'botao_registro_background_modal'=> '#00FFFF',
            'botao_registro_border_nav'     => '#00FFFF',
            'botao_deposito_border_saq'     => '#00FFFF',
            'botao_deposito_background_dep'=> '#00FFFF',
            'botao_deposito_border_dep'     => '#00FFFF',
            'botao_deposito_background_saq'=> '#00FFFF',
    
            // Grupo Secundário
            'search_back'                   => '#7FFFD4',
            'placeholder_background'        => '#7FFFD4',
            'card_transaction'              => '#7FFFD4',
            'background_color_category'     => '#7FFFD4',
            'background_bottom_navigation'  => '#7FFFD4',
            'background_bottom_navigation_dark' => '#7FFFD4',
            'footer_color'                  => '#7FFFD4',
            'footer_color_dark'             => '#7FFFD4',
            'side_menu'                     => '#7FFFD4',
            'side_menu_dark'                => '#7FFFD4',
            'navtop_color'                  => '#7FFFD4',
            'navtop_color_dark'             => '#7FFFD4',
    
            // Grupo Terciário
            'item_sub_color'                => '#40E0D0',
            'background_color_jackpot'      => '#40E0D0',
            'value_color_jackpot'           => '#40E0D0',
            'sidebar_color'                 => '#40E0D0',
            'sidebar_color_dark'            => '#40E0D0',
            'background_base'               => '#40E0D0',
            'background_base_dark'          => '#40E0D0',
            'background_color_cassino'      => '#40E0D0',
    
            // Grupo Quaternário
            'search_border_color'           => '#20B2AA',
            'borders_and_dividers_colors'   => '#20B2AA',
        ],
    
        'magenta' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#FF00FF',
            'bonus_color_dep'               => '#FF00FF',
            'color_players'                 => '#FF00FF',
            'back_sub_color'                => '#FF00FF',
            'botao_deposito_background_nav' => '#FF00FF',
            'botao_login_background_nav'    => '#FF00FF',
            'botao_login_background_modal'  => '#FF00FF',
            'botao_registro_background_modal'=> '#FF00FF',
            'botao_registro_border_nav'     => '#FF00FF',
            'botao_deposito_border_saq'     => '#FF00FF',
            'botao_deposito_background_dep'=> '#FF00FF',
            'botao_deposito_border_dep'     => '#FF00FF',
            'botao_deposito_background_saq'=> '#FF00FF',
    
            // Grupo Secundário
            'search_back'                   => '#FF77FF',
            'placeholder_background'        => '#FF77FF',
            'card_transaction'              => '#FF77FF',
            'background_color_category'     => '#FF77FF',
            'background_bottom_navigation'  => '#FF77FF',
            'background_bottom_navigation_dark' => '#FF77FF',
            'footer_color'                  => '#FF77FF',
            'footer_color_dark'             => '#FF77FF',
            'side_menu'                     => '#FF77FF',
            'side_menu_dark'                => '#FF77FF',
            'navtop_color'                  => '#FF77FF',
            'navtop_color_dark'             => '#FF77FF',
    
            // Grupo Terciário
            'item_sub_color'                => '#D147A3',
            'background_color_jackpot'      => '#D147A3',
            'value_color_jackpot'           => '#D147A3',
            'sidebar_color'                 => '#D147A3',
            'sidebar_color_dark'            => '#D147A3',
            'background_base'               => '#D147A3',
            'background_base_dark'          => '#D147A3',
            'background_color_cassino'      => '#D147A3',
    
            // Grupo Quaternário
            'search_border_color'           => '#B030B0',
            'borders_and_dividers_colors'   => '#B030B0',
        ],
    
        'teal' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#008080',
            'bonus_color_dep'               => '#008080',
            'color_players'                 => '#008080',
            'back_sub_color'                => '#008080',
            'botao_deposito_background_nav' => '#008080',
            'botao_login_background_nav'    => '#008080',
            'botao_login_background_modal'  => '#008080',
            'botao_registro_background_modal'=> '#008080',
            'botao_registro_border_nav'     => '#008080',
            'botao_deposito_border_saq'     => '#008080',
            'botao_deposito_background_dep'=> '#008080',
            'botao_deposito_border_dep'     => '#008080',
            'botao_deposito_background_saq'=> '#008080',
    
            // Grupo Secundário
            'search_back'                   => '#20B2AA',
            'placeholder_background'        => '#20B2AA',
            'card_transaction'              => '#20B2AA',
            'background_color_category'     => '#20B2AA',
            'background_bottom_navigation'  => '#20B2AA',
            'background_bottom_navigation_dark' => '#20B2AA',
            'footer_color'                  => '#20B2AA',
            'footer_color_dark'             => '#20B2AA',
            'side_menu'                     => '#20B2AA',
            'side_menu_dark'                => '#20B2AA',
            'navtop_color'                  => '#20B2AA',
            'navtop_color_dark'             => '#20B2AA',
    
            // Grupo Terciário
            'item_sub_color'                => '#66CDAA',
            'background_color_jackpot'      => '#66CDAA',
            'value_color_jackpot'           => '#66CDAA',
            'sidebar_color'                 => '#66CDAA',
            'sidebar_color_dark'            => '#66CDAA',
            'background_base'               => '#66CDAA',
            'background_base_dark'          => '#66CDAA',
            'background_color_cassino'      => '#66CDAA',
    
            // Grupo Quaternário
            'search_border_color'           => '#5F9EA0',
            'borders_and_dividers_colors'   => '#5F9EA0',
        ],
    
        'indigo' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#4B0082',
            'bonus_color_dep'               => '#4B0082',
            'color_players'                 => '#4B0082',
            'back_sub_color'                => '#4B0082',
            'botao_deposito_background_nav' => '#4B0082',
            'botao_login_background_nav'    => '#4B0082',
            'botao_login_background_modal'  => '#4B0082',
            'botao_registro_background_modal'=> '#4B0082',
            'botao_registro_border_nav'     => '#4B0082',
            'botao_deposito_border_saq'     => '#4B0082',
            'botao_deposito_background_dep'=> '#4B0082',
            'botao_deposito_border_dep'     => '#4B0082',
            'botao_deposito_background_saq'=> '#4B0082',
    
            // Grupo Secundário
            'search_back'                   => '#6A5ACD',
            'placeholder_background'        => '#6A5ACD',
            'card_transaction'              => '#6A5ACD',
            'background_color_category'     => '#6A5ACD',
            'background_bottom_navigation'  => '#6A5ACD',
            'background_bottom_navigation_dark' => '#6A5ACD',
            'footer_color'                  => '#6A5ACD',
            'footer_color_dark'             => '#6A5ACD',
            'side_menu'                     => '#6A5ACD',
            'side_menu_dark'                => '#6A5ACD',
            'navtop_color'                  => '#6A5ACD',
            'navtop_color_dark'             => '#6A5ACD',
    
            // Grupo Terciário
            'item_sub_color'                => '#9370DB',
            'background_color_jackpot'      => '#9370DB',
            'value_color_jackpot'           => '#9370DB',
            'sidebar_color'                 => '#9370DB',
            'sidebar_color_dark'            => '#9370DB',
            'background_base'               => '#9370DB',
            'background_base_dark'          => '#9370DB',
            'background_color_cassino'      => '#9370DB',
    
            // Grupo Quaternário
            'search_border_color'           => '#8A2BE2',
            'borders_and_dividers_colors'   => '#8A2BE2',
        ],
    
        'coral' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#FF7F50',
            'bonus_color_dep'               => '#FF7F50',
            'color_players'                 => '#FF7F50',
            'back_sub_color'                => '#FF7F50',
            'botao_deposito_background_nav' => '#FF7F50',
            'botao_login_background_nav'    => '#FF7F50',
            'botao_login_background_modal'  => '#FF7F50',
            'botao_registro_background_modal'=> '#FF7F50',
            'botao_registro_border_nav'     => '#FF7F50',
            'botao_deposito_border_saq'     => '#FF7F50',
            'botao_deposito_background_dep'=> '#FF7F50',
            'botao_deposito_border_dep'     => '#FF7F50',
            'botao_deposito_background_saq'=> '#FF7F50',
    
            // Grupo Secundário
            'search_back'                   => '#FF9966',
            'placeholder_background'        => '#FF9966',
            'card_transaction'              => '#FF9966',
            'background_color_category'     => '#FF9966',
            'background_bottom_navigation'  => '#FF9966',
            'background_bottom_navigation_dark' => '#FF9966',
            'footer_color'                  => '#FF9966',
            'footer_color_dark'             => '#FF9966',
            'side_menu'                     => '#FF9966',
            'side_menu_dark'                => '#FF9966',
            'navtop_color'                  => '#FF9966',
            'navtop_color_dark'             => '#FF9966',
    
            // Grupo Terciário
            'item_sub_color'                => '#FF7F50',
            'background_color_jackpot'      => '#FF7F50',
            'value_color_jackpot'           => '#FF7F50',
            'sidebar_color'                 => '#FF7F50',
            'sidebar_color_dark'            => '#FF7F50',
            'background_base'               => '#FF7F50',
            'background_base_dark'          => '#FF7F50',
            'background_color_cassino'      => '#FF7F50',
    
            // Grupo Quaternário
            'search_border_color'           => '#FF6347',
            'borders_and_dividers_colors'   => '#FF6347',
        ],
    
        'navy' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#000080',
            'bonus_color_dep'               => '#000080',
            'color_players'                 => '#000080',
            'back_sub_color'                => '#000080',
            'botao_deposito_background_nav' => '#000080',
            'botao_login_background_nav'    => '#000080',
            'botao_login_background_modal'  => '#000080',
            'botao_registro_background_modal'=> '#000080',
            'botao_registro_border_nav'     => '#000080',
            'botao_deposito_border_saq'     => '#000080',
            'botao_deposito_background_dep'=> '#000080',
            'botao_deposito_border_dep'     => '#000080',
            'botao_deposito_background_saq'=> '#000080',
    
            // Grupo Secundário
            'search_back'                   => '#00008B',
            'placeholder_background'        => '#00008B',
            'card_transaction'              => '#00008B',
            'background_color_category'     => '#00008B',
            'background_bottom_navigation'  => '#00008B',
            'background_bottom_navigation_dark' => '#00008B',
            'footer_color'                  => '#00008B',
            'footer_color_dark'             => '#00008B',
            'side_menu'                     => '#00008B',
            'side_menu_dark'                => '#00008B',
            'navtop_color'                  => '#00008B',
            'navtop_color_dark'             => '#00008B',
    
            // Grupo Terciário
            'item_sub_color'                => '#4169E1',
            'background_color_jackpot'      => '#4169E1',
            'value_color_jackpot'           => '#4169E1',
            'sidebar_color'                 => '#4169E1',
            'sidebar_color_dark'            => '#4169E1',
            'background_base'               => '#4169E1',
            'background_base_dark'          => '#4169E1',
            'background_color_cassino'      => '#4169E1',
    
            // Grupo Quaternário
            'search_border_color'           => '#4682B4',
            'borders_and_dividers_colors'   => '#4682B4',
        ],
    
        'mint' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#98FF98',
            'bonus_color_dep'               => '#98FF98',
            'color_players'                 => '#98FF98',
            'back_sub_color'                => '#98FF98',
            'botao_deposito_background_nav' => '#98FF98',
            'botao_login_background_nav'    => '#98FF98',
            'botao_login_background_modal'  => '#98FF98',
            'botao_registro_background_modal'=> '#98FF98',
            'botao_registro_border_nav'     => '#98FF98',
            'botao_deposito_border_saq'     => '#98FF98',
            'botao_deposito_background_dep'=> '#98FF98',
            'botao_deposito_border_dep'     => '#98FF98',
            'botao_deposito_background_saq'=> '#98FF98',
    
            // Grupo Secundário
            'search_back'                   => '#AAF0D1',
            'placeholder_background'        => '#AAF0D1',
            'card_transaction'              => '#AAF0D1',
            'background_color_category'     => '#AAF0D1',
            'background_bottom_navigation'  => '#AAF0D1',
            'background_bottom_navigation_dark' => '#AAF0D1',
            'footer_color'                  => '#AAF0D1',
            'footer_color_dark'             => '#AAF0D1',
            'side_menu'                     => '#AAF0D1',
            'side_menu_dark'                => '#AAF0D1',
            'navtop_color'                  => '#AAF0D1',
            'navtop_color_dark'             => '#AAF0D1',
    
            // Grupo Terciário
            'item_sub_color'                => '#90EE90',
            'background_color_jackpot'      => '#90EE90',
            'value_color_jackpot'           => '#90EE90',
            'sidebar_color'                 => '#90EE90',
            'sidebar_color_dark'            => '#90EE90',
            'background_base'               => '#90EE90',
            'background_base_dark'          => '#90EE90',
            'background_color_cassino'      => '#90EE90',
    
            // Grupo Quaternário
            'search_border_color'           => '#32CD32',
            'borders_and_dividers_colors'   => '#32CD32',
        ],
    
        'crimson' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#DC143C',
            'bonus_color_dep'               => '#DC143C',
            'color_players'                 => '#DC143C',
            'back_sub_color'                => '#DC143C',
            'botao_deposito_background_nav' => '#DC143C',
            'botao_login_background_nav'    => '#DC143C',
            'botao_login_background_modal'  => '#DC143C',
            'botao_registro_background_modal'=> '#DC143C',
            'botao_registro_border_nav'     => '#DC143C',
            'botao_deposito_border_saq'     => '#DC143C',
            'botao_deposito_background_dep'=> '#DC143C',
            'botao_deposito_border_dep'     => '#DC143C',
            'botao_deposito_background_saq'=> '#DC143C',
    
            // Grupo Secundário
            'search_back'                   => '#E9967A',
            'placeholder_background'        => '#E9967A',
            'card_transaction'              => '#E9967A',
            'background_color_category'     => '#E9967A',
            'background_bottom_navigation'  => '#E9967A',
            'background_bottom_navigation_dark' => '#E9967A',
            'footer_color'                  => '#E9967A',
            'footer_color_dark'             => '#E9967A',
            'side_menu'                     => '#E9967A',
            'side_menu_dark'                => '#E9967A',
            'navtop_color'                  => '#E9967A',
            'navtop_color_dark'             => '#E9967A',
    
            // Grupo Terciário
            'item_sub_color'                => '#CD5C5C',
            'background_color_jackpot'      => '#CD5C5C',
            'value_color_jackpot'           => '#CD5C5C',
            'sidebar_color'                 => '#CD5C5C',
            'sidebar_color_dark'            => '#CD5C5C',
            'background_base'               => '#CD5C5C',
            'background_base_dark'          => '#CD5C5C',
            'background_color_cassino'      => '#CD5C5C',
    
            // Grupo Quaternário
            'search_border_color'           => '#B22222',
            'borders_and_dividers_colors'   => '#B22222',
        ],
    
        'sapphire' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#0F52BA',
            'bonus_color_dep'               => '#0F52BA',
            'color_players'                 => '#0F52BA',
            'back_sub_color'                => '#0F52BA',
            'botao_deposito_background_nav' => '#0F52BA',
            'botao_login_background_nav'    => '#0F52BA',
            'botao_login_background_modal'  => '#0F52BA',
            'botao_registro_background_modal'=> '#0F52BA',
            'botao_registro_border_nav'     => '#0F52BA',
            'botao_deposito_border_saq'     => '#0F52BA',
            'botao_deposito_background_dep'=> '#0F52BA',
            'botao_deposito_border_dep'     => '#0F52BA',
            'botao_deposito_background_saq'=> '#0F52BA',
    
            // Grupo Secundário
            'search_back'                   => '#4169E1',
            'placeholder_background'        => '#4169E1',
            'card_transaction'              => '#4169E1',
            'background_color_category'     => '#4169E1',
            'background_bottom_navigation'  => '#4169E1',
            'background_bottom_navigation_dark' => '#4169E1',
            'footer_color'                  => '#4169E1',
            'footer_color_dark'             => '#4169E1',
            'side_menu'                     => '#4169E1',
            'side_menu_dark'                => '#4169E1',
            'navtop_color'                  => '#4169E1',
            'navtop_color_dark'             => '#4169E1',
    
            // Grupo Terciário
            'item_sub_color'                => '#87CEFA',
            'background_color_jackpot'      => '#87CEFA',
            'value_color_jackpot'           => '#87CEFA',
            'sidebar_color'                 => '#87CEFA',
            'sidebar_color_dark'            => '#87CEFA',
            'background_base'               => '#87CEFA',
            'background_base_dark'          => '#87CEFA',
            'background_color_cassino'      => '#87CEFA',
    
            // Grupo Quaternário
            'search_border_color'           => '#1E90FF',
            'borders_and_dividers_colors'   => '#1E90FF',
        ],
    
        'olive' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#808000',
            'bonus_color_dep'               => '#808000',
            'color_players'                 => '#808000',
            'back_sub_color'                => '#808000',
            'botao_deposito_background_nav' => '#808000',
            'botao_login_background_nav'    => '#808000',
            'botao_login_background_modal'  => '#808000',
            'botao_registro_background_modal'=> '#808000',
            'botao_registro_border_nav'     => '#808000',
            'botao_deposito_border_saq'     => '#808000',
            'botao_deposito_background_dep'=> '#808000',
            'botao_deposito_border_dep'     => '#808000',
            'botao_deposito_background_saq'=> '#808000',
    
            // Grupo Secundário
            'search_back'                   => '#9ACD32',
            'placeholder_background'        => '#9ACD32',
            'card_transaction'              => '#9ACD32',
            'background_color_category'     => '#9ACD32',
            'background_bottom_navigation'  => '#9ACD32',
            'background_bottom_navigation_dark' => '#9ACD32',
            'footer_color'                  => '#9ACD32',
            'footer_color_dark'             => '#9ACD32',
            'side_menu'                     => '#9ACD32',
            'side_menu_dark'                => '#9ACD32',
            'navtop_color'                  => '#9ACD32',
            'navtop_color_dark'             => '#9ACD32',
    
            // Grupo Terciário
            'item_sub_color'                => '#6B8E23',
            'background_color_jackpot'      => '#6B8E23',
            'value_color_jackpot'           => '#6B8E23',
            'sidebar_color'                 => '#6B8E23',
            'sidebar_color_dark'            => '#6B8E23',
            'background_base'               => '#6B8E23',
            'background_base_dark'          => '#6B8E23',
            'background_color_cassino'      => '#6B8E23',
    
            // Grupo Quaternário
            'search_border_color'           => '#556B2F',
            'borders_and_dividers_colors'   => '#556B2F',
        ],
    
        'copper' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#B87333',
            'bonus_color_dep'               => '#B87333',
            'color_players'                 => '#B87333',
            'back_sub_color'                => '#B87333',
            'botao_deposito_background_nav' => '#B87333',
            'botao_login_background_nav'    => '#B87333',
            'botao_login_background_modal'  => '#B87333',
            'botao_registro_background_modal'=> '#B87333',
            'botao_registro_border_nav'     => '#B87333',
            'botao_deposito_border_saq'     => '#B87333',
            'botao_deposito_background_dep'=> '#B87333',
            'botao_deposito_border_dep'     => '#B87333',
            'botao_deposito_background_saq'=> '#B87333',
    
            // Grupo Secundário
            'search_back'                   => '#D2691E',
            'placeholder_background'        => '#D2691E',
            'card_transaction'              => '#D2691E',
            'background_color_category'     => '#D2691E',
            'background_bottom_navigation'  => '#D2691E',
            'background_bottom_navigation_dark' => '#D2691E',
            'footer_color'                  => '#D2691E',
            'footer_color_dark'             => '#D2691E',
            'side_menu'                     => '#D2691E',
            'side_menu_dark'                => '#D2691E',
            'navtop_color'                  => '#D2691E',
            'navtop_color_dark'             => '#D2691E',
    
            // Grupo Terciário
            'item_sub_color'                => '#CD853F',
            'background_color_jackpot'      => '#CD853F',
            'value_color_jackpot'           => '#CD853F',
            'sidebar_color'                 => '#CD853F',
            'sidebar_color_dark'            => '#CD853F',
            'background_base'               => '#CD853F',
            'background_base_dark'          => '#CD853F',
            'background_color_cassino'      => '#CD853F',
    
            // Grupo Quaternário
            'search_border_color'           => '#A0522D',
            'borders_and_dividers_colors'   => '#A0522D',
        ],
    
        'ruby' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#E0115F',
            'bonus_color_dep'               => '#E0115F',
            'color_players'                 => '#E0115F',
            'back_sub_color'                => '#E0115F',
            'botao_deposito_background_nav' => '#E0115F',
            'botao_login_background_nav'    => '#E0115F',
            'botao_login_background_modal'  => '#E0115F',
            'botao_registro_background_modal'=> '#E0115F',
            'botao_registro_border_nav'     => '#E0115F',
            'botao_deposito_border_saq'     => '#E0115F',
            'botao_deposito_background_dep'=> '#E0115F',
            'botao_deposito_border_dep'     => '#E0115F',
            'botao_deposito_background_saq'=> '#E0115F',
    
            // Grupo Secundário
            'search_back'                   => '#FF66CC',
            'placeholder_background'        => '#FF66CC',
            'card_transaction'              => '#FF66CC',
            'background_color_category'     => '#FF66CC',
            'background_bottom_navigation'  => '#FF66CC',
            'background_bottom_navigation_dark' => '#FF66CC',
            'footer_color'                  => '#FF66CC',
            'footer_color_dark'             => '#FF66CC',
            'side_menu'                     => '#FF66CC',
            'side_menu_dark'                => '#FF66CC',
            'navtop_color'                  => '#FF66CC',
            'navtop_color_dark'             => '#FF66CC',
    
            // Grupo Terciário
            'item_sub_color'                => '#C71585',
            'background_color_jackpot'      => '#C71585',
            'value_color_jackpot'           => '#C71585',
            'sidebar_color'                 => '#C71585',
            'sidebar_color_dark'            => '#C71585',
            'background_base'               => '#C71585',
            'background_base_dark'          => '#C71585',
            'background_color_cassino'      => '#C71585',
    
            // Grupo Quaternário
            'search_border_color'           => '#8B0000',
            'borders_and_dividers_colors'   => '#8B0000',
        ],
    
        'amethyst' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#9966CC',
            'bonus_color_dep'               => '#9966CC',
            'color_players'                 => '#9966CC',
            'back_sub_color'                => '#9966CC',
            'botao_deposito_background_nav' => '#9966CC',
            'botao_login_background_nav'    => '#9966CC',
            'botao_login_background_modal'  => '#9966CC',
            'botao_registro_background_modal'=> '#9966CC',
            'botao_registro_border_nav'     => '#9966CC',
            'botao_deposito_border_saq'     => '#9966CC',
            'botao_deposito_background_dep'=> '#9966CC',
            'botao_deposito_border_dep'     => '#9966CC',
            'botao_deposito_background_saq'=> '#9966CC',
    
            // Grupo Secundário
            'search_back'                   => '#B19CD9',
            'placeholder_background'        => '#B19CD9',
            'card_transaction'              => '#B19CD9',
            'background_color_category'     => '#B19CD9',
            'background_bottom_navigation'  => '#B19CD9',
            'background_bottom_navigation_dark' => '#B19CD9',
            'footer_color'                  => '#B19CD9',
            'footer_color_dark'             => '#B19CD9',
            'side_menu'                     => '#B19CD9',
            'side_menu_dark'                => '#B19CD9',
            'navtop_color'                  => '#B19CD9',
            'navtop_color_dark'             => '#B19CD9',
    
            // Grupo Terciário
            'item_sub_color'                => '#A9A9F5',
            'background_color_jackpot'      => '#A9A9F5',
            'value_color_jackpot'           => '#A9A9F5',
            'sidebar_color'                 => '#A9A9F5',
            'sidebar_color_dark'            => '#A9A9F5',
            'background_base'               => '#A9A9F5',
            'background_base_dark'          => '#A9A9F5',
            'background_color_cassino'      => '#A9A9F5',
    
            // Grupo Quaternário
            'search_border_color'           => '#8A2BE2',
            'borders_and_dividers_colors'   => '#8A2BE2',
        ],
    
        'peach' => [
            // Grupo Primário
            'Border_bottons_and_selected'   => '#FFDAB9',
            'bonus_color_dep'               => '#FFDAB9',
            'color_players'                 => '#FFDAB9',
            'back_sub_color'                => '#FFDAB9',
            'botao_deposito_background_nav' => '#FFDAB9',
            'botao_login_background_nav'    => '#FFDAB9',
            'botao_login_background_modal'  => '#FFDAB9',
            'botao_registro_background_modal'=> '#FFDAB9',
            'botao_registro_border_nav'     => '#FFDAB9',
            'botao_deposito_border_saq'     => '#FFDAB9',
            'botao_deposito_background_dep'=> '#FFDAB9',
            'botao_deposito_border_dep'     => '#FFDAB9',
            'botao_deposito_background_saq'=> '#FFDAB9',
    
            // Grupo Secundário
            'search_back'                   => '#FFE5B4',
            'placeholder_background'        => '#FFE5B4',
            'card_transaction'              => '#FFE5B4',
            'background_color_category'     => '#FFE5B4',
            'background_bottom_navigation'  => '#FFE5B4',
            'background_bottom_navigation_dark' => '#FFE5B4',
            'footer_color'                  => '#FFE5B4',
            'footer_color_dark'             => '#FFE5B4',
            'side_menu'                     => '#FFE5B4',
            'side_menu_dark'                => '#FFE5B4',
            'navtop_color'                  => '#FFE5B4',
            'navtop_color_dark'             => '#FFE5B4',
    
            // Grupo Terciário
            'item_sub_color'                => '#FFD1DC',
            'background_color_jackpot'      => '#FFD1DC',
            'value_color_jackpot'           => '#FFD1DC',
            'sidebar_color'                 => '#FFD1DC',
            'sidebar_color_dark'            => '#FFD1DC',
            'background_base'               => '#FFD1DC',
            'background_base_dark'          => '#FFD1DC',
            'background_color_cassino'      => '#FFD1DC',
    
            // Grupo Quaternário
            'search_border_color'           => '#FFB6C1',
            'borders_and_dividers_colors'   => '#FFB6C1',
        ],
        'fierycontrast' => [
        // Grupo Primário – acentos em vermelho
        'Border_bottons_and_selected'    => '#B22222',
        'bonus_color_dep'                => '#B22222',
        'color_players'                  => '#B22222',
        'back_sub_color'                 => '#B22222',
        'botao_deposito_background_nav'  => '#B22222',
        'botao_login_background_nav'     => '#B22222',
        'botao_login_background_modal'   => '#B22222',
        'botao_registro_background_modal'=> '#B22222',
        'botao_registro_border_nav'      => '#B22222',
        'botao_deposito_border_saq'      => '#B22222',
        'botao_deposito_background_dep'  => '#B22222',
        'botao_deposito_border_dep'      => '#B22222',
        'botao_deposito_background_saq'  => '#B22222',

        // Grupo Secundário – fundos escuros (marrom muito profundo)
        'search_back'                    => '#3F1A1A',
        'placeholder_background'         => '#3F1A1A',
        'card_transaction'               => '#3F1A1A',
        'background_color_category'      => '#3F1A1A',
        'background_bottom_navigation'   => '#3F1A1A',
        'background_bottom_navigation_dark'=> '#3F1A1A',
        'footer_color'                   => '#3F1A1A',
        'footer_color_dark'              => '#3F1A1A',
        'side_menu'                      => '#3F1A1A',
        'side_menu_dark'                 => '#3F1A1A',
        'navtop_color'                   => '#3F1A1A',
        'navtop_color_dark'              => '#3F1A1A',

        // Grupo Terciário – textos e fundos base (tom intermediário, evitando o branco)
        'item_sub_color'                 => '#7F2A2A',
        'background_color_jackpot'       => '#7F2A2A',
        'value_color_jackpot'            => '#7F2A2A',
        'sidebar_color'                  => '#7F2A2A',
        'sidebar_color_dark'             => '#7F2A2A',
        'background_base'                => '#7F2A2A',
        'background_base_dark'           => '#7F2A2A',
        'background_color_cassino'       => '#7F2A2A',

        // Grupo Quaternário – bordas
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'oceansunrise' => [
        // Grupo Primário – acentos em azul
        'Border_bottons_and_selected'    => '#1E90FF',
        'bonus_color_dep'                => '#1E90FF',
        'color_players'                  => '#1E90FF',
        'back_sub_color'                 => '#1E90FF',
        'botao_deposito_background_nav'  => '#1E90FF',
        'botao_login_background_nav'     => '#1E90FF',
        'botao_login_background_modal'   => '#1E90FF',
        'botao_registro_background_modal'=> '#1E90FF',
        'botao_registro_border_nav'      => '#1E90FF',
        'botao_deposito_border_saq'      => '#1E90FF',
        'botao_deposito_background_dep'  => '#1E90FF',
        'botao_deposito_border_dep'      => '#1E90FF',
        'botao_deposito_background_saq'  => '#1E90FF',

        // Grupo Secundário – fundos escuros (laranja queimado, escurecido)
        'search_back'                    => '#7F2000',
        'placeholder_background'         => '#7F2000',
        'card_transaction'               => '#7F2000',
        'background_color_category'      => '#7F2000',
        'background_bottom_navigation'   => '#7F2000',
        'background_bottom_navigation_dark'=> '#7F2000',
        'footer_color'                   => '#7F2000',
        'footer_color_dark'              => '#7F2000',
        'side_menu'                      => '#7F2000',
        'side_menu_dark'                 => '#7F2000',
        'navtop_color'                   => '#7F2000',
        'navtop_color_dark'              => '#7F2000',

        // Grupo Terciário – textos e base em tom siena
        'item_sub_color'                 => '#A0522D',
        'background_color_jackpot'       => '#A0522D',
        'value_color_jackpot'            => '#A0522D',
        'sidebar_color'                  => '#A0522D',
        'sidebar_color_dark'             => '#A0522D',
        'background_base'                => '#A0522D',
        'background_base_dark'           => '#A0522D',
        'background_color_cassino'       => '#A0522D',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'forestglow' => [
        // Grupo Primário – acentos em verde
        'Border_bottons_and_selected'    => '#228B22',
        'bonus_color_dep'                => '#228B22',
        'color_players'                  => '#228B22',
        'back_sub_color'                 => '#228B22',
        'botao_deposito_background_nav'  => '#228B22',
        'botao_login_background_nav'     => '#228B22',
        'botao_login_background_modal'   => '#228B22',
        'botao_registro_background_modal'=> '#228B22',
        'botao_registro_border_nav'      => '#228B22',
        'botao_deposito_border_saq'      => '#228B22',
        'botao_deposito_background_dep'  => '#228B22',
        'botao_deposito_border_dep'      => '#228B22',
        'botao_deposito_background_saq'  => '#228B22',

        // Grupo Secundário – fundos escuros (marrom, similar ao original)
        'search_back'                    => '#3E2723',
        'placeholder_background'         => '#3E2723',
        'card_transaction'               => '#3E2723',
        'background_color_category'      => '#3E2723',
        'background_bottom_navigation'   => '#3E2723',
        'background_bottom_navigation_dark'=> '#3E2723',
        'footer_color'                   => '#3E2723',
        'footer_color_dark'              => '#3E2723',
        'side_menu'                      => '#3E2723',
        'side_menu_dark'                 => '#3E2723',
        'navtop_color'                   => '#3E2723',
        'navtop_color_dark'              => '#3E2723',

        // Grupo Terciário – textos e base em tom mais claro de marrom
        'item_sub_color'                 => '#5E3A2C',
        'background_color_jackpot'       => '#5E3A2C',
        'value_color_jackpot'            => '#5E3A2C',
        'sidebar_color'                  => '#5E3A2C',
        'sidebar_color_dark'             => '#5E3A2C',
        'background_base'                => '#5E3A2C',
        'background_base_dark'           => '#5E3A2C',
        'background_color_cassino'       => '#5E3A2C',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'electricsky' => [
        // Grupo Primário – acentos em azul claro
        'Border_bottons_and_selected'    => '#00BFFF',
        'bonus_color_dep'                => '#00BFFF',
        'color_players'                  => '#00BFFF',
        'back_sub_color'                 => '#00BFFF',
        'botao_deposito_background_nav'  => '#00BFFF',
        'botao_login_background_nav'     => '#00BFFF',
        'botao_login_background_modal'   => '#00BFFF',
        'botao_registro_background_modal'=> '#00BFFF',
        'botao_registro_border_nav'      => '#00BFFF',
        'botao_deposito_border_saq'      => '#00BFFF',
        'botao_deposito_background_dep'  => '#00BFFF',
        'botao_deposito_border_dep'      => '#00BFFF',
        'botao_deposito_background_saq'  => '#00BFFF',

        // Grupo Secundário – fundos escuros (tom de azul profundo)
        'search_back'                    => '#191970',
        'placeholder_background'         => '#191970',
        'card_transaction'               => '#191970',
        'background_color_category'      => '#191970',
        'background_bottom_navigation'   => '#191970',
        'background_bottom_navigation_dark'=> '#191970',
        'footer_color'                   => '#191970',
        'footer_color_dark'              => '#191970',
        'side_menu'                      => '#191970',
        'side_menu_dark'                 => '#191970',
        'navtop_color'                   => '#191970',
        'navtop_color_dark'              => '#191970',

        // Grupo Terciário – textos e base em tom azul médio
        'item_sub_color'                 => '#3F51B5',
        'background_color_jackpot'       => '#3F51B5',
        'value_color_jackpot'            => '#3F51B5',
        'sidebar_color'                  => '#3F51B5',
        'sidebar_color_dark'             => '#3F51B5',
        'background_base'                => '#3F51B5',
        'background_base_dark'           => '#3F51B5',
        'background_color_cassino'       => '#3F51B5',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'urbanchic' => [
        // Grupo Primário – acentos em azul-violeta
        'Border_bottons_and_selected'    => '#8A2BE2',
        'bonus_color_dep'                => '#8A2BE2',
        'color_players'                  => '#8A2BE2',
        'back_sub_color'                 => '#8A2BE2',
        'botao_deposito_background_nav'  => '#8A2BE2',
        'botao_login_background_nav'     => '#8A2BE2',
        'botao_login_background_modal'   => '#8A2BE2',
        'botao_registro_background_modal'=> '#8A2BE2',
        'botao_registro_border_nav'      => '#8A2BE2',
        'botao_deposito_border_saq'      => '#8A2BE2',
        'botao_deposito_background_dep'  => '#8A2BE2',
        'botao_deposito_border_dep'      => '#8A2BE2',
        'botao_deposito_background_saq'  => '#8A2BE2',

        // Grupo Secundário – fundos escuros (cinza quase preto)
        'search_back'                    => '#2C2C2C',
        'placeholder_background'         => '#2C2C2C',
        'card_transaction'               => '#2C2C2C',
        'background_color_category'      => '#2C2C2C',
        'background_bottom_navigation'   => '#2C2C2C',
        'background_bottom_navigation_dark'=> '#2C2C2C',
        'footer_color'                   => '#2C2C2C',
        'footer_color_dark'              => '#2C2C2C',
        'side_menu'                      => '#2C2C2C',
        'side_menu_dark'                 => '#2C2C2C',
        'navtop_color'                   => '#2C2C2C',
        'navtop_color_dark'              => '#2C2C2C',

        // Grupo Terciário – textos e base com matiz violeta escuro
        'item_sub_color'                 => '#4B3D75',
        'background_color_jackpot'       => '#4B3D75',
        'value_color_jackpot'            => '#4B3D75',
        'sidebar_color'                  => '#4B3D75',
        'sidebar_color_dark'             => '#4B3D75',
        'background_base'                => '#4B3D75',
        'background_base_dark'           => '#4B3D75',
        'background_color_cassino'       => '#4B3D75',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'sunsetdream' => [
        // Grupo Primário – acentos em coral
        'Border_bottons_and_selected'    => '#FF7F50',
        'bonus_color_dep'                => '#FF7F50',
        'color_players'                  => '#FF7F50',
        'back_sub_color'                 => '#FF7F50',
        'botao_deposito_background_nav'  => '#FF7F50',
        'botao_login_background_nav'     => '#FF7F50',
        'botao_login_background_modal'   => '#FF7F50',
        'botao_registro_background_modal'=> '#FF7F50',
        'botao_registro_border_nav'      => '#FF7F50',
        'botao_deposito_border_saq'      => '#FF7F50',
        'botao_deposito_background_dep'  => '#FF7F50',
        'botao_deposito_border_dep'      => '#FF7F50',
        'botao_deposito_background_saq'  => '#FF7F50',

        // Grupo Secundário – fundos escuros (tom indigo profundo)
        'search_back'                    => '#4B0082',
        'placeholder_background'         => '#4B0082',
        'card_transaction'               => '#4B0082',
        'background_color_category'      => '#4B0082',
        'background_bottom_navigation'   => '#4B0082',
        'background_bottom_navigation_dark'=> '#4B0082',
        'footer_color'                   => '#4B0082',
        'footer_color_dark'              => '#4B0082',
        'side_menu'                      => '#4B0082',
        'side_menu_dark'                 => '#4B0082',
        'navtop_color'                   => '#4B0082',
        'navtop_color_dark'              => '#4B0082',

        // Grupo Terciário – textos e base em tom púrpura médio
        'item_sub_color'                 => '#551A8B',
        'background_color_jackpot'       => '#551A8B',
        'value_color_jackpot'            => '#551A8B',
        'sidebar_color'                  => '#551A8B',
        'sidebar_color_dark'             => '#551A8B',
        'background_base'                => '#551A8B',
        'background_base_dark'           => '#551A8B',
        'background_color_cassino'       => '#551A8B',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'tropicalvibe' => [
        // Grupo Primário – acentos em turquesa
        'Border_bottons_and_selected'    => '#40E0D0',
        'bonus_color_dep'                => '#40E0D0',
        'color_players'                  => '#40E0D0',
        'back_sub_color'                 => '#40E0D0',
        'botao_deposito_background_nav'  => '#40E0D0',
        'botao_login_background_nav'     => '#40E0D0',
        'botao_login_background_modal'   => '#40E0D0',
        'botao_registro_background_modal'=> '#40E0D0',
        'botao_registro_border_nav'      => '#40E0D0',
        'botao_deposito_border_saq'      => '#40E0D0',
        'botao_deposito_background_dep'  => '#40E0D0',
        'botao_deposito_border_dep'      => '#40E0D0',
        'botao_deposito_background_saq'  => '#40E0D0',

        // Grupo Secundário – fundos escuros (verde musgo)
        'search_back'                    => '#006400',
        'placeholder_background'         => '#006400',
        'card_transaction'               => '#006400',
        'background_color_category'      => '#006400',
        'background_bottom_navigation'   => '#006400',
        'background_bottom_navigation_dark'=> '#006400',
        'footer_color'                   => '#006400',
        'footer_color_dark'              => '#006400',
        'side_menu'                      => '#006400',
        'side_menu_dark'                 => '#006400',
        'navtop_color'                   => '#006400',
        'navtop_color_dark'              => '#006400',

        // Grupo Terciário – textos e base em tom verde marítimo
        'item_sub_color'                 => '#2E8B57',
        'background_color_jackpot'       => '#2E8B57',
        'value_color_jackpot'            => '#2E8B57',
        'sidebar_color'                  => '#2E8B57',
        'sidebar_color_dark'             => '#2E8B57',
        'background_base'                => '#2E8B57',
        'background_base_dark'           => '#2E8B57',
        'background_color_cassino'       => '#2E8B57',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'midnightaurora' => [
        // Grupo Primário – acentos em roxo
        'Border_bottons_and_selected'    => '#800080',
        'bonus_color_dep'                => '#800080',
        'color_players'                  => '#800080',
        'back_sub_color'                 => '#800080',
        'botao_deposito_background_nav'  => '#800080',
        'botao_login_background_nav'     => '#800080',
        'botao_login_background_modal'   => '#800080',
        'botao_registro_background_modal'=> '#800080',
        'botao_registro_border_nav'      => '#800080',
        'botao_deposito_border_saq'      => '#800080',
        'botao_deposito_background_dep'  => '#800080',
        'botao_deposito_border_dep'      => '#800080',
        'botao_deposito_background_saq'  => '#800080',

        // Grupo Secundário – fundos escuros (teal profundo)
        'search_back'                    => '#004953',
        'placeholder_background'         => '#004953',
        'card_transaction'               => '#004953',
        'background_color_category'      => '#004953',
        'background_bottom_navigation'   => '#004953',
        'background_bottom_navigation_dark'=> '#004953',
        'footer_color'                   => '#004953',
        'footer_color_dark'              => '#004953',
        'side_menu'                      => '#004953',
        'side_menu_dark'                 => '#004953',
        'navtop_color'                   => '#004953',
        'navtop_color_dark'              => '#004953',

        // Grupo Terciário – textos e base em tom azul-arroxeado
        'item_sub_color'                 => '#483D8B',
        'background_color_jackpot'       => '#483D8B',
        'value_color_jackpot'            => '#483D8B',
        'sidebar_color'                  => '#483D8B',
        'sidebar_color_dark'             => '#483D8B',
        'background_base'                => '#483D8B',
        'background_base_dark'           => '#483D8B',
        'background_color_cassino'       => '#483D8B',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'vibrantcitrus' => [
        // Grupo Primário – acentos em verde limão
        'Border_bottons_and_selected'    => '#32CD32',
        'bonus_color_dep'                => '#32CD32',
        'color_players'                  => '#32CD32',
        'back_sub_color'                 => '#32CD32',
        'botao_deposito_background_nav'  => '#32CD32',
        'botao_login_background_nav'     => '#32CD32',
        'botao_login_background_modal'   => '#32CD32',
        'botao_registro_background_modal'=> '#32CD32',
        'botao_registro_border_nav'      => '#32CD32',
        'botao_deposito_border_saq'      => '#32CD32',
        'botao_deposito_background_dep'  => '#32CD32',
        'botao_deposito_border_dep'      => '#32CD32',
        'botao_deposito_background_saq'  => '#32CD32',

        // Grupo Secundário – fundos escuros (laranja escuro)
        'search_back'                    => '#8B4000',
        'placeholder_background'         => '#8B4000',
        'card_transaction'               => '#8B4000',
        'background_color_category'      => '#8B4000',
        'background_bottom_navigation'   => '#8B4000',
        'background_bottom_navigation_dark'=> '#8B4000',
        'footer_color'                   => '#8B4000',
        'footer_color_dark'              => '#8B4000',
        'side_menu'                      => '#8B4000',
        'side_menu_dark'                 => '#8B4000',
        'navtop_color'                   => '#8B4000',
        'navtop_color_dark'              => '#8B4000',

        // Grupo Terciário – textos e base em tom "peru"
        'item_sub_color'                 => '#CD853F',
        'background_color_jackpot'       => '#CD853F',
        'value_color_jackpot'            => '#CD853F',
        'sidebar_color'                  => '#CD853F',
        'sidebar_color_dark'             => '#CD853F',
        'background_base'                => '#CD853F',
        'background_base_dark'           => '#CD853F',
        'background_color_cassino'       => '#CD853F',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'royalelegance' => [
        // Grupo Primário – acentos em azul real
        'Border_bottons_and_selected'    => '#4169E1',
        'bonus_color_dep'                => '#4169E1',
        'color_players'                  => '#4169E1',
        'back_sub_color'                 => '#4169E1',
        'botao_deposito_background_nav'  => '#4169E1',
        'botao_login_background_nav'     => '#4169E1',
        'botao_login_background_modal'   => '#4169E1',
        'botao_registro_background_modal'=> '#4169E1',
        'botao_registro_border_nav'      => '#4169E1',
        'botao_deposito_border_saq'      => '#4169E1',
        'botao_deposito_background_dep'  => '#4169E1',
        'botao_deposito_border_dep'      => '#4169E1',
        'botao_deposito_background_saq'  => '#4169E1',

        // Grupo Secundário – fundos escuros (dourado escuro)
        'search_back'                    => '#8B7500',
        'placeholder_background'         => '#8B7500',
        'card_transaction'               => '#8B7500',
        'background_color_category'      => '#8B7500',
        'background_bottom_navigation'   => '#8B7500',
        'background_bottom_navigation_dark'=> '#8B7500',
        'footer_color'                   => '#8B7500',
        'footer_color_dark'              => '#8B7500',
        'side_menu'                      => '#8B7500',
        'side_menu_dark'                 => '#8B7500',
        'navtop_color'                   => '#8B7500',
        'navtop_color_dark'              => '#8B7500',

        // Grupo Terciário – textos e base em tom dourado claro
        'item_sub_color'                 => '#A57C00',
        'background_color_jackpot'       => '#A57C00',
        'value_color_jackpot'            => '#A57C00',
        'sidebar_color'                  => '#A57C00',
        'sidebar_color_dark'             => '#A57C00',
        'background_base'                => '#A57C00',
        'background_base_dark'           => '#A57C00',
        'background_color_cassino'       => '#A57C00',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'rusticcharm' => [
        // Grupo Primário – acentos em marrom rústico
        'Border_bottons_and_selected'    => '#8B4513',
        'bonus_color_dep'                => '#8B4513',
        'color_players'                  => '#8B4513',
        'back_sub_color'                 => '#8B4513',
        'botao_deposito_background_nav'  => '#8B4513',
        'botao_login_background_nav'     => '#8B4513',
        'botao_login_background_modal'   => '#8B4513',
        'botao_registro_background_modal'=> '#8B4513',
        'botao_registro_border_nav'      => '#8B4513',
        'botao_deposito_border_saq'      => '#8B4513',
        'botao_deposito_background_dep'  => '#8B4513',
        'botao_deposito_border_dep'      => '#8B4513',
        'botao_deposito_background_saq'  => '#8B4513',

        // Grupo Secundário – fundos escuros (verde oliva)
        'search_back'                    => '#556B2F',
        'placeholder_background'         => '#556B2F',
        'card_transaction'               => '#556B2F',
        'background_color_category'      => '#556B2F',
        'background_bottom_navigation'   => '#556B2F',
        'background_bottom_navigation_dark'=> '#556B2F',
        'footer_color'                   => '#556B2F',
        'footer_color_dark'              => '#556B2F',
        'side_menu'                      => '#556B2F',
        'side_menu_dark'                 => '#556B2F',
        'navtop_color'                   => '#556B2F',
        'navtop_color_dark'              => '#556B2F',

        // Grupo Terciário – textos e base em tom oliva (mais claro)
        'item_sub_color'                 => '#6B8E23',
        'background_color_jackpot'       => '#6B8E23',
        'value_color_jackpot'            => '#6B8E23',
        'sidebar_color'                  => '#6B8E23',
        'sidebar_color_dark'             => '#6B8E23',
        'background_base'                => '#6B8E23',
        'background_base_dark'           => '#6B8E23',
        'background_color_cassino'       => '#6B8E23',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'icecrystal' => [
        // Grupo Primário – acentos em azul celeste
        'Border_bottons_and_selected'    => '#87CEFA',
        'bonus_color_dep'                => '#87CEFA',
        'color_players'                  => '#87CEFA',
        'back_sub_color'                 => '#87CEFA',
        'botao_deposito_background_nav'  => '#87CEFA',
        'botao_login_background_nav'     => '#87CEFA',
        'botao_login_background_modal'   => '#87CEFA',
        'botao_registro_background_modal'=> '#87CEFA',
        'botao_registro_border_nav'      => '#87CEFA',
        'botao_deposito_border_saq'      => '#87CEFA',
        'botao_deposito_background_dep'  => '#87CEFA',
        'botao_deposito_border_dep'      => '#87CEFA',
        'botao_deposito_background_saq'  => '#87CEFA',

        // Grupo Secundário – fundos escuros (azul profundo)
        'search_back'                    => '#0D47A1',
        'placeholder_background'         => '#0D47A1',
        'card_transaction'               => '#0D47A1',
        'background_color_category'      => '#0D47A1',
        'background_bottom_navigation'   => '#0D47A1',
        'background_bottom_navigation_dark'=> '#0D47A1',
        'footer_color'                   => '#0D47A1',
        'footer_color_dark'              => '#0D47A1',
        'side_menu'                      => '#0D47A1',
        'side_menu_dark'                 => '#0D47A1',
        'navtop_color'                   => '#0D47A1',
        'navtop_color_dark'              => '#0D47A1',

        // Grupo Terciário – textos e base em tom azul médio
        'item_sub_color'                 => '#1E88E5',
        'background_color_jackpot'       => '#1E88E5',
        'value_color_jackpot'            => '#1E88E5',
        'sidebar_color'                  => '#1E88E5',
        'sidebar_color_dark'             => '#1E88E5',
        'background_base'                => '#1E88E5',
        'background_base_dark'           => '#1E88E5',
        'background_color_cassino'       => '#1E88E5',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'modernmonochrome' => [
        // Grupo Primário – acentos em cinza
        'Border_bottons_and_selected'    => '#424242',
        'bonus_color_dep'                => '#424242',
        'color_players'                  => '#424242',
        'back_sub_color'                 => '#424242',
        'botao_deposito_background_nav'  => '#424242',
        'botao_login_background_nav'     => '#424242',
        'botao_login_background_modal'   => '#424242',
        'botao_registro_background_modal'=> '#424242',
        'botao_registro_border_nav'      => '#424242',
        'botao_deposito_border_saq'      => '#424242',
        'botao_deposito_background_dep'  => '#424242',
        'botao_deposito_border_dep'      => '#424242',
        'botao_deposito_background_saq'  => '#424242',

        // Grupo Secundário – fundos escuros (cinza muito profundo)
        'search_back'                    => '#212121',
        'placeholder_background'         => '#212121',
        'card_transaction'               => '#212121',
        'background_color_category'      => '#212121',
        'background_bottom_navigation'   => '#212121',
        'background_bottom_navigation_dark'=> '#212121',
        'footer_color'                   => '#212121',
        'footer_color_dark'              => '#212121',
        'side_menu'                      => '#212121',
        'side_menu_dark'                 => '#212121',
        'navtop_color'                   => '#212121',
        'navtop_color_dark'              => '#212121',

        // Grupo Terciário – textos e base em cinza intermediário
        'item_sub_color'                 => '#2E2E2E',
        'background_color_jackpot'       => '#2E2E2E',
        'value_color_jackpot'            => '#2E2E2E',
        'sidebar_color'                  => '#2E2E2E',
        'sidebar_color_dark'             => '#2E2E2E',
        'background_base'                => '#2E2E2E',
        'background_base_dark'           => '#2E2E2E',
        'background_color_cassino'       => '#2E2E2E',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'sunnybreeze' => [
        // Grupo Primário – acentos em azul celeste
        'Border_bottons_and_selected'    => '#87CEEB',
        'bonus_color_dep'                => '#87CEEB',
        'color_players'                  => '#87CEEB',
        'back_sub_color'                 => '#87CEEB',
        'botao_deposito_background_nav'  => '#87CEEB',
        'botao_login_background_nav'     => '#87CEEB',
        'botao_login_background_modal'   => '#87CEEB',
        'botao_registro_background_modal'=> '#87CEEB',
        'botao_registro_border_nav'      => '#87CEEB',
        'botao_deposito_border_saq'      => '#87CEEB',
        'botao_deposito_background_dep'  => '#87CEEB',
        'botao_deposito_border_dep'      => '#87CEEB',
        'botao_deposito_background_saq'  => '#87CEEB',

        // Grupo Secundário – fundos escuros (ciano profundo)
        'search_back'                    => '#008B8B',
        'placeholder_background'         => '#008B8B',
        'card_transaction'               => '#008B8B',
        'background_color_category'      => '#008B8B',
        'background_bottom_navigation'   => '#008B8B',
        'background_bottom_navigation_dark'=> '#008B8B',
        'footer_color'                   => '#008B8B',
        'footer_color_dark'              => '#008B8B',
        'side_menu'                      => '#008B8B',
        'side_menu_dark'                 => '#008B8B',
        'navtop_color'                   => '#008B8B',
        'navtop_color_dark'              => '#008B8B',

        // Grupo Terciário – textos e base em tom ciano claro
        'item_sub_color'                 => '#00ACC1',
        'background_color_jackpot'       => '#00ACC1',
        'value_color_jackpot'            => '#00ACC1',
        'sidebar_color'                  => '#00ACC1',
        'sidebar_color_dark'             => '#00ACC1',
        'background_base'                => '#00ACC1',
        'background_base_dark'           => '#00ACC1',
        'background_color_cassino'       => '#00ACC1',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    'radiantbloom' => [
        // Grupo Primário – acentos em magenta vibrante
        'Border_bottons_and_selected'    => '#FF00FF',
        'bonus_color_dep'                => '#FF00FF',
        'color_players'                  => '#FF00FF',
        'back_sub_color'                 => '#FF00FF',
        'botao_deposito_background_nav'  => '#FF00FF',
        'botao_login_background_nav'     => '#FF00FF',
        'botao_login_background_modal'   => '#FF00FF',
        'botao_registro_background_modal'=> '#FF00FF',
        'botao_registro_border_nav'      => '#FF00FF',
        'botao_deposito_border_saq'      => '#FF00FF',
        'botao_deposito_background_dep'  => '#FF00FF',
        'botao_deposito_border_dep'      => '#FF00FF',
        'botao_deposito_background_saq'  => '#FF00FF',

        // Grupo Secundário – fundos escuros (verde escuro)
        'search_back'                    => '#006400',
        'placeholder_background'         => '#006400',
        'card_transaction'               => '#006400',
        'background_color_category'      => '#006400',
        'background_bottom_navigation'   => '#006400',
        'background_bottom_navigation_dark'=> '#006400',
        'footer_color'                   => '#006400',
        'footer_color_dark'              => '#006400',
        'side_menu'                      => '#006400',
        'side_menu_dark'                 => '#006400',
        'navtop_color'                   => '#006400',
        'navtop_color_dark'              => '#006400',

        // Grupo Terciário – textos e base em tom verde floresta
        'item_sub_color'                 => '#228B22',
        'background_color_jackpot'       => '#228B22',
        'value_color_jackpot'            => '#228B22',
        'sidebar_color'                  => '#228B22',
        'sidebar_color_dark'             => '#228B22',
        'background_base'                => '#228B22',
        'background_base_dark'           => '#228B22',
        'background_color_cassino'       => '#228B22',

        // Grupo Quaternário
        'search_border_color'            => '#D3D3D3',
        'borders_and_dividers_colors'    => '#D3D3D3',
    ],

    ];

    if (array_key_exists($theme, $themes)) {
        $themeData = $themes[$theme];

        // Atualize o banco de dados com os valores do tema escolhido
        \DB::table('custom_layouts')->update([

            'Border_bottons_and_selected' => $themeData['Border_bottons_and_selected'],
            'bonus_color_dep' => $themeData['bonus_color_dep'],
            'color_players' => $themeData['color_players'],
            'back_sub_color' => $themeData['back_sub_color'],
            'botao_deposito_background_nav' => $themeData['botao_deposito_background_nav'],
            'botao_login_background_nav' => $themeData['botao_login_background_nav'],
            'botao_login_background_modal' => $themeData['botao_login_background_modal'],
            'botao_registro_background_modal' => $themeData['botao_registro_background_modal'],
            'botao_registro_border_nav' => $themeData['botao_registro_border_nav'],
            'botao_deposito_border_saq' => $themeData['botao_deposito_border_saq'],
            'botao_deposito_background_dep' => $themeData['botao_deposito_background_dep'],
            'botao_deposito_border_dep' => $themeData['botao_deposito_border_dep'],
            'botao_deposito_background_saq' => $themeData['botao_deposito_background_saq'],

            'search_back' => $themeData['search_back'],
            'placeholder_background' => $themeData['placeholder_background'],
            'card_transaction' => $themeData['card_transaction'],
            'background_color_category' => $themeData['background_color_category'],
            'background_bottom_navigation' => $themeData['background_bottom_navigation'],
            'background_bottom_navigation_dark' => $themeData['background_bottom_navigation_dark'],
            'footer_color' => $themeData['footer_color'],
            'footer_color_dark' => $themeData['footer_color_dark'],
            'side_menu' => $themeData['side_menu'],
            'side_menu_dark' => $themeData['side_menu_dark'],
            'navtop_color' => $themeData['navtop_color'],
            'navtop_color_dark' => $themeData['navtop_color_dark'],

            'item_sub_color' => $themeData['item_sub_color'],
            'background_color_jackpot' => $themeData['background_color_jackpot'],
            'value_color_jackpot' => $themeData['value_color_jackpot'],
            'sidebar_color' => $themeData['sidebar_color'],
            'sidebar_color_dark' => $themeData['sidebar_color_dark'],
            'background_base' => $themeData['background_base'],
            'background_base_dark' => $themeData['background_base_dark'],
            'background_color_cassino' => $themeData['background_color_cassino'],

            'search_border_color' => $themeData['search_border_color'],
            'borders_and_dividers_colors' => $themeData['borders_and_dividers_colors'],                  

        ]);

        return true;
    }

    return false;
}
}

return [
    'themes' => [
        // Temas Originais
        'pourple'    => 'Pourple',
        'black'      => 'Black',
        'blue'       => 'Blue',
        'red'        => 'Red',
        'pink'       => 'Pink',
        'limon'      => 'Limon',
        'brown'      => 'Brown',
        'skyblue'    => 'Skyblue',
        'whiteblue'  => 'Whiteblue',
        'greendark'  => 'Greendark',
        'orange'     => 'Orange',
        'green'      => 'Green',
        'yellow'     => 'Yellow',
        'greenwhite' => 'Greenwhite',
        'gray'       => 'Gray',
        'violet'     => 'Violet',
        'aqua'       => 'Aqua',
        'magenta'    => 'Magenta',
        'teal'       => 'Teal',
        'indigo'     => 'Indigo',
        'coral'      => 'Coral',
        'navy'       => 'Navy',
        'mint'       => 'Mint',
        'crimson'    => 'Crimson',
        'sapphire'   => 'Sapphire',
        'olive'      => 'Olive',
        'copper'     => 'Copper',
        'ruby'       => 'Ruby',
        'amethyst'   => 'Amethyst',
        'peach'      => 'Peach',

        // 15 Novos Temas com combinações de cores contrastantes
        'fierycontrast'    => 'Fiery Contrast',
        'oceansunrise'     => 'Ocean Sunrise',
        'forestglow'       => 'Forest Glow',
        'electricsky'      => 'Electric Sky',
        'urbanchic'        => 'Urban Chic',
        'sunsetdream'      => 'Sunset Dream',
        'tropicalvibe'     => 'Tropical Vibe',
        'midnightaurora'   => 'Midnight Aurora',
        'vibrantcitrus'    => 'Vibrant Citrus',
        'royalelegance'    => 'Royale Elegance',
        'rusticcharm'      => 'Rustic Charm',
        'icecrystal'       => 'Ice Crystal',
        'modernmonochrome' => 'Modern Monochrome',
        'sunnybreeze'      => 'Sunny Breeze',
        'radiantbloom'     => 'Radiant Bloom',
    ],

];